package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbUserInformation<M extends BaseTbUserInformation<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
		return (M)this;
	}
	
	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public M setAreaCode(java.lang.String areaCode) {
		set("area_code", areaCode);
		return (M)this;
	}
	
	public java.lang.String getAreaCode() {
		return getStr("area_code");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setSex(java.lang.Integer sex) {
		set("sex", sex);
		return (M)this;
	}
	
	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	public M setOpenBank(java.lang.String openBank) {
		set("open_bank", openBank);
		return (M)this;
	}
	
	public java.lang.String getOpenBank() {
		return getStr("open_bank");
	}

	public M setBankCardNumber(java.lang.String bankCardNumber) {
		set("bank_card_number", bankCardNumber);
		return (M)this;
	}
	
	public java.lang.String getBankCardNumber() {
		return getStr("bank_card_number");
	}

	public M setIdCardNumber(java.lang.String idCardNumber) {
		set("id_card_number", idCardNumber);
		return (M)this;
	}
	
	public java.lang.String getIdCardNumber() {
		return getStr("id_card_number");
	}

	public M setIdCardImgFront(java.lang.String idCardImgFront) {
		set("id_card_img_front", idCardImgFront);
		return (M)this;
	}
	
	public java.lang.String getIdCardImgFront() {
		return getStr("id_card_img_front");
	}

	public M setIdCardImgBack(java.lang.String idCardImgBack) {
		set("id_card_img_back", idCardImgBack);
		return (M)this;
	}
	
	public java.lang.String getIdCardImgBack() {
		return getStr("id_card_img_back");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setDriverName(java.lang.String driverName) {
		set("driver_name", driverName);
		return (M)this;
	}
	
	public java.lang.String getDriverName() {
		return getStr("driver_name");
	}

	public M setDriverBirthday(java.util.Date driverBirthday) {
		set("driver_birthday", driverBirthday);
		return (M)this;
	}
	
	public java.util.Date getDriverBirthday() {
		return get("driver_birthday");
	}

	public M setDriverAreaCode(java.lang.String driverAreaCode) {
		set("driver_area_code", driverAreaCode);
		return (M)this;
	}
	
	public java.lang.String getDriverAreaCode() {
		return getStr("driver_area_code");
	}

	public M setDriverSex(java.lang.Integer driverSex) {
		set("driver_sex", driverSex);
		return (M)this;
	}
	
	public java.lang.Integer getDriverSex() {
		return getInt("driver_sex");
	}

	public M setDriverAddress(java.lang.String driverAddress) {
		set("driver_address", driverAddress);
		return (M)this;
	}
	
	public java.lang.String getDriverAddress() {
		return getStr("driver_address");
	}

	public M setDriverBankCardNumber(java.lang.String driverBankCardNumber) {
		set("driver_bank_card_number", driverBankCardNumber);
		return (M)this;
	}
	
	public java.lang.String getDriverBankCardNumber() {
		return getStr("driver_bank_card_number");
	}

	public M setDriverIdCardNumber(java.lang.String driverIdCardNumber) {
		set("driver_id_card_number", driverIdCardNumber);
		return (M)this;
	}
	
	public java.lang.String getDriverIdCardNumber() {
		return getStr("driver_id_card_number");
	}

	public M setDriverIdCardImgFront(java.lang.String driverIdCardImgFront) {
		set("driver_id_card_img_front", driverIdCardImgFront);
		return (M)this;
	}
	
	public java.lang.String getDriverIdCardImgFront() {
		return getStr("driver_id_card_img_front");
	}

	public M setDriverIdCardImgBack(java.lang.String driverIdCardImgBack) {
		set("driver_id_card_img_back", driverIdCardImgBack);
		return (M)this;
	}
	
	public java.lang.String getDriverIdCardImgBack() {
		return getStr("driver_id_card_img_back");
	}

	public M setDriverPhone(java.lang.String driverPhone) {
		set("driver_phone", driverPhone);
		return (M)this;
	}
	
	public java.lang.String getDriverPhone() {
		return getStr("driver_phone");
	}

	public M setTravelLicenceImgFront(java.lang.String travelLicenceImgFront) {
		set("travel_licence_img_front", travelLicenceImgFront);
		return (M)this;
	}
	
	public java.lang.String getTravelLicenceImgFront() {
		return getStr("travel_licence_img_front");
	}

	public M setTravelLicenceImgBack(java.lang.String travelLicenceImgBack) {
		set("travel_licence_img_back", travelLicenceImgBack);
		return (M)this;
	}
	
	public java.lang.String getTravelLicenceImgBack() {
		return getStr("travel_licence_img_back");
	}

	public M setDriverLicenceType(java.lang.String driverLicenceType) {
		set("driver_licence_type", driverLicenceType);
		return (M)this;
	}
	
	public java.lang.String getDriverLicenceType() {
		return getStr("driver_licence_type");
	}

	public M setDriverAge(java.lang.Integer driverAge) {
		set("driver_age", driverAge);
		return (M)this;
	}
	
	public java.lang.Integer getDriverAge() {
		return getInt("driver_age");
	}

	public M setDriverLicenceImgFront(java.lang.String driverLicenceImgFront) {
		set("driver_licence_img_front", driverLicenceImgFront);
		return (M)this;
	}
	
	public java.lang.String getDriverLicenceImgFront() {
		return getStr("driver_licence_img_front");
	}

	public M setDriverLicenceImgBack(java.lang.String driverLicenceImgBack) {
		set("driver_licence_img_back", driverLicenceImgBack);
		return (M)this;
	}
	
	public java.lang.String getDriverLicenceImgBack() {
		return getStr("driver_licence_img_back");
	}

	public M setPlateNumber(java.lang.String plateNumber) {
		set("plate_number", plateNumber);
		return (M)this;
	}
	
	public java.lang.String getPlateNumber() {
		return getStr("plate_number");
	}

	public M setBrand(java.lang.String brand) {
		set("brand", brand);
		return (M)this;
	}
	
	public java.lang.String getBrand() {
		return getStr("brand");
	}

	public M setModel(java.lang.String model) {
		set("model", model);
		return (M)this;
	}
	
	public java.lang.String getModel() {
		return getStr("model");
	}

	public M setMotorcycleType(java.lang.String motorcycleType) {
		set("motorcycle_type", motorcycleType);
		return (M)this;
	}
	
	public java.lang.String getMotorcycleType() {
		return getStr("motorcycle_type");
	}

	public M setCarPhoto1(java.lang.String carPhoto1) {
		set("car_photo1", carPhoto1);
		return (M)this;
	}
	
	public java.lang.String getCarPhoto1() {
		return getStr("car_photo1");
	}

	public M setCarPhoto2(java.lang.String carPhoto2) {
		set("car_photo2", carPhoto2);
		return (M)this;
	}
	
	public java.lang.String getCarPhoto2() {
		return getStr("car_photo2");
	}

	public M setBuyDate(java.util.Date buyDate) {
		set("buy_date", buyDate);
		return (M)this;
	}
	
	public java.util.Date getBuyDate() {
		return get("buy_date");
	}

	public M setInsuranceBeginDate(java.util.Date insuranceBeginDate) {
		set("insurance_begin_date", insuranceBeginDate);
		return (M)this;
	}
	
	public java.util.Date getInsuranceBeginDate() {
		return get("insurance_begin_date");
	}

	public M setInsuranceEndDate(java.util.Date insuranceEndDate) {
		set("insurance_end_date", insuranceEndDate);
		return (M)this;
	}
	
	public java.util.Date getInsuranceEndDate() {
		return get("insurance_end_date");
	}

	public M setInsuranceFilePhoto1(java.lang.String insuranceFilePhoto1) {
		set("insurance_file_photo1", insuranceFilePhoto1);
		return (M)this;
	}
	
	public java.lang.String getInsuranceFilePhoto1() {
		return getStr("insurance_file_photo1");
	}

	public M setInsuranceFilePhoto2(java.lang.String insuranceFilePhoto2) {
		set("insurance_file_photo2", insuranceFilePhoto2);
		return (M)this;
	}
	
	public java.lang.String getInsuranceFilePhoto2() {
		return getStr("insurance_file_photo2");
	}

	public M setCarState(java.lang.Integer carState) {
		set("car_state", carState);
		return (M)this;
	}
	
	public java.lang.Integer getCarState() {
		return getInt("car_state");
	}

	public M setCarProperty(java.lang.Integer carProperty) {
		set("car_property", carProperty);
		return (M)this;
	}
	
	public java.lang.Integer getCarProperty() {
		return getInt("car_property");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setTotalMileage(java.lang.Float totalMileage) {
		set("total_mileage", totalMileage);
		return (M)this;
	}
	
	public java.lang.Float getTotalMileage() {
		return getFloat("total_mileage");
	}

	public M setTotalTime(java.lang.Float totalTime) {
		set("total_time", totalTime);
		return (M)this;
	}
	
	public java.lang.Float getTotalTime() {
		return getFloat("total_time");
	}

	public M setTotalOrder(java.lang.Integer totalOrder) {
		set("total_order", totalOrder);
		return (M)this;
	}
	
	public java.lang.Integer getTotalOrder() {
		return getInt("total_order");
	}

	public M setDriverOpenBank(java.lang.String driverOpenBank) {
		set("driver_open_bank", driverOpenBank);
		return (M)this;
	}
	
	public java.lang.String getDriverOpenBank() {
		return getStr("driver_open_bank");
	}

	public M setDriverBankNum(java.lang.String driverBankNum) {
		set("driver_bank_num", driverBankNum);
		return (M)this;
	}
	
	public java.lang.String getDriverBankNum() {
		return getStr("driver_bank_num");
	}

}
