package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbOrder<M extends BaseTbOrder<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOrderCode(java.lang.String orderCode) {
		set("order_code", orderCode);
		return (M)this;
	}
	
	public java.lang.String getOrderCode() {
		return getStr("order_code");
	}

	public M setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
		return (M)this;
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}

	public M setProjectCode(java.lang.String projectCode) {
		set("project_code", projectCode);
		return (M)this;
	}
	
	public java.lang.String getProjectCode() {
		return getStr("project_code");
	}

	public M setProjectType(java.lang.Integer projectType) {
		set("project_type", projectType);
		return (M)this;
	}
	
	public java.lang.Integer getProjectType() {
		return getInt("project_type");
	}

	public M setTransportType(java.lang.Integer transportType) {
		set("transport_type", transportType);
		return (M)this;
	}
	
	public java.lang.Integer getTransportType() {
		return getInt("transport_type");
	}

	public M setDriverId(java.lang.Integer driverId) {
		set("driver_id", driverId);
		return (M)this;
	}
	
	public java.lang.Integer getDriverId() {
		return getInt("driver_id");
	}

	public M setCreatorId(java.lang.Integer creatorId) {
		set("creator_id", creatorId);
		return (M)this;
	}
	
	public java.lang.Integer getCreatorId() {
		return getInt("creator_id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setUserDispatchId(java.lang.Integer userDispatchId) {
		set("user_dispatch_id", userDispatchId);
		return (M)this;
	}
	
	public java.lang.Integer getUserDispatchId() {
		return getInt("user_dispatch_id");
	}

	public M setUserDispatchName(java.lang.String userDispatchName) {
		set("user_dispatch_name", userDispatchName);
		return (M)this;
	}
	
	public java.lang.String getUserDispatchName() {
		return getStr("user_dispatch_name");
	}

	public M setProjectDistributionId(java.lang.Integer projectDistributionId) {
		set("project_distribution_id", projectDistributionId);
		return (M)this;
	}
	
	public java.lang.Integer getProjectDistributionId() {
		return getInt("project_distribution_id");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setExceptionStatus(java.lang.Integer exceptionStatus) {
		set("exception_status", exceptionStatus);
		return (M)this;
	}
	
	public java.lang.Integer getExceptionStatus() {
		return getInt("exception_status");
	}

	public M setExceptionId(java.lang.Integer exceptionId) {
		set("exception_id", exceptionId);
		return (M)this;
	}
	
	public java.lang.Integer getExceptionId() {
		return getInt("exception_id");
	}

	public M setExceptionReoportId(java.lang.Integer exceptionReoportId) {
		set("exception_reoport_id", exceptionReoportId);
		return (M)this;
	}
	
	public java.lang.Integer getExceptionReoportId() {
		return getInt("exception_reoport_id");
	}

	public M setExceptionReoportName(java.lang.String exceptionReoportName) {
		set("exception_reoport_name", exceptionReoportName);
		return (M)this;
	}
	
	public java.lang.String getExceptionReoportName() {
		return getStr("exception_reoport_name");
	}

	public M setExceptionTime(java.util.Date exceptionTime) {
		set("exception_time", exceptionTime);
		return (M)this;
	}
	
	public java.util.Date getExceptionTime() {
		return get("exception_time");
	}

	public M setExceptionReoportReason(java.lang.String exceptionReoportReason) {
		set("exception_reoport_reason", exceptionReoportReason);
		return (M)this;
	}
	
	public java.lang.String getExceptionReoportReason() {
		return getStr("exception_reoport_reason");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setStepSelectCode(java.lang.Integer stepSelectCode) {
		set("step_select_code", stepSelectCode);
		return (M)this;
	}
	
	public java.lang.Integer getStepSelectCode() {
		return getInt("step_select_code");
	}

	public M setStepSelect(java.lang.String stepSelect) {
		set("step_select", stepSelect);
		return (M)this;
	}
	
	public java.lang.String getStepSelect() {
		return getStr("step_select");
	}

	public M setBranchId(java.lang.Integer branchId) {
		set("branch_id", branchId);
		return (M)this;
	}
	
	public java.lang.Integer getBranchId() {
		return getInt("branch_id");
	}

	public M setBranchGroupName(java.lang.String branchGroupName) {
		set("branch_group_name", branchGroupName);
		return (M)this;
	}
	
	public java.lang.String getBranchGroupName() {
		return getStr("branch_group_name");
	}

	public M setSendCompanyId(java.lang.Integer sendCompanyId) {
		set("send_company_id", sendCompanyId);
		return (M)this;
	}
	
	public java.lang.Integer getSendCompanyId() {
		return getInt("send_company_id");
	}

	public M setSendCompany(java.lang.String sendCompany) {
		set("send_company", sendCompany);
		return (M)this;
	}
	
	public java.lang.String getSendCompany() {
		return getStr("send_company");
	}

	public M setPickupPlace(java.lang.String pickupPlace) {
		set("pickup_place", pickupPlace);
		return (M)this;
	}
	
	public java.lang.String getPickupPlace() {
		return getStr("pickup_place");
	}

	public M setPickupPlaceAddress(java.lang.String pickupPlaceAddress) {
		set("pickup_place_address", pickupPlaceAddress);
		return (M)this;
	}
	
	public java.lang.String getPickupPlaceAddress() {
		return getStr("pickup_place_address");
	}

	public M setReceiptCompanyId(java.lang.Integer receiptCompanyId) {
		set("receipt_company_id", receiptCompanyId);
		return (M)this;
	}
	
	public java.lang.Integer getReceiptCompanyId() {
		return getInt("receipt_company_id");
	}

	public M setReceiptCompany(java.lang.String receiptCompany) {
		set("receipt_company", receiptCompany);
		return (M)this;
	}
	
	public java.lang.String getReceiptCompany() {
		return getStr("receipt_company");
	}

	public M setArrivePlace(java.lang.String arrivePlace) {
		set("arrive_place", arrivePlace);
		return (M)this;
	}
	
	public java.lang.String getArrivePlace() {
		return getStr("arrive_place");
	}

	public M setArriveAddress(java.lang.String arriveAddress) {
		set("arrive_address", arriveAddress);
		return (M)this;
	}
	
	public java.lang.String getArriveAddress() {
		return getStr("arrive_address");
	}

	public M setArriveFreightYrad(java.lang.String arriveFreightYrad) {
		set("arrive_freight_yrad", arriveFreightYrad);
		return (M)this;
	}
	
	public java.lang.String getArriveFreightYrad() {
		return getStr("arrive_freight_yrad");
	}

	public M setArriveFreightSite(java.lang.String arriveFreightSite) {
		set("arrive_freight_site", arriveFreightSite);
		return (M)this;
	}
	
	public java.lang.String getArriveFreightSite() {
		return getStr("arrive_freight_site");
	}

	public M setCarrierVehicleId(java.lang.String carrierVehicleId) {
		set("carrier_vehicle_id", carrierVehicleId);
		return (M)this;
	}
	
	public java.lang.String getCarrierVehicleId() {
		return getStr("carrier_vehicle_id");
	}

	public M setCarrierVehicleName(java.lang.String carrierVehicleName) {
		set("carrier_vehicle_name", carrierVehicleName);
		return (M)this;
	}
	
	public java.lang.String getCarrierVehicleName() {
		return getStr("carrier_vehicle_name");
	}

	public M setCarPlateNumber(java.lang.String carPlateNumber) {
		set("car_plate_number", carPlateNumber);
		return (M)this;
	}
	
	public java.lang.String getCarPlateNumber() {
		return getStr("car_plate_number");
	}

	public M setCarType(java.lang.String carType) {
		set("car_type", carType);
		return (M)this;
	}
	
	public java.lang.String getCarType() {
		return getStr("car_type");
	}

	public M setDriverName(java.lang.String driverName) {
		set("driver_name", driverName);
		return (M)this;
	}
	
	public java.lang.String getDriverName() {
		return getStr("driver_name");
	}

	public M setDriverPhone(java.lang.String driverPhone) {
		set("driver_phone", driverPhone);
		return (M)this;
	}
	
	public java.lang.String getDriverPhone() {
		return getStr("driver_phone");
	}

	public M setContainerNumber1Id(java.lang.String containerNumber1Id) {
		set("container_number1_id", containerNumber1Id);
		return (M)this;
	}
	
	public java.lang.String getContainerNumber1Id() {
		return getStr("container_number1_id");
	}

	public M setContainerNumber1(java.lang.String containerNumber1) {
		set("container_number1", containerNumber1);
		return (M)this;
	}
	
	public java.lang.String getContainerNumber1() {
		return getStr("container_number1");
	}

	public M setContainerNumber2Id(java.lang.String containerNumber2Id) {
		set("container_number2_id", containerNumber2Id);
		return (M)this;
	}
	
	public java.lang.String getContainerNumber2Id() {
		return getStr("container_number2_id");
	}

	public M setContainerNumber2(java.lang.String containerNumber2) {
		set("container_number2", containerNumber2);
		return (M)this;
	}
	
	public java.lang.String getContainerNumber2() {
		return getStr("container_number2");
	}

	public M setCargoName(java.lang.String cargoName) {
		set("cargo_name", cargoName);
		return (M)this;
	}
	
	public java.lang.String getCargoName() {
		return getStr("cargo_name");
	}

	public M setSpecifications(java.lang.String specifications) {
		set("specifications", specifications);
		return (M)this;
	}
	
	public java.lang.String getSpecifications() {
		return getStr("specifications");
	}

	public M setDeductionRate(java.math.BigDecimal deductionRate) {
		set("deduction_rate", deductionRate);
		return (M)this;
	}
	
	public java.math.BigDecimal getDeductionRate() {
		return get("deduction_rate");
	}

	public M setShortBargeCost(java.math.BigDecimal shortBargeCost) {
		set("short_barge_cost", shortBargeCost);
		return (M)this;
	}
	
	public java.math.BigDecimal getShortBargeCost() {
		return get("short_barge_cost");
	}

	public M setSubsidy(java.math.BigDecimal subsidy) {
		set("subsidy", subsidy);
		return (M)this;
	}
	
	public java.math.BigDecimal getSubsidy() {
		return get("subsidy");
	}

	public M setDeductionPrice(java.math.BigDecimal deductionPrice) {
		set("deduction_price", deductionPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getDeductionPrice() {
		return get("deduction_price");
	}

	public M setSendTare(java.math.BigDecimal sendTare) {
		set("send_tare", sendTare);
		return (M)this;
	}
	
	public java.math.BigDecimal getSendTare() {
		return get("send_tare");
	}

	public M setSendGross(java.math.BigDecimal sendGross) {
		set("send_gross", sendGross);
		return (M)this;
	}
	
	public java.math.BigDecimal getSendGross() {
		return get("send_gross");
	}

	public M setContainerOneSendNet(java.math.BigDecimal containerOneSendNet) {
		set("container_one_send_net", containerOneSendNet);
		return (M)this;
	}
	
	public java.math.BigDecimal getContainerOneSendNet() {
		return get("container_one_send_net");
	}

	public M setContainerTwoSendNet(java.math.BigDecimal containerTwoSendNet) {
		set("container_two_send_net", containerTwoSendNet);
		return (M)this;
	}
	
	public java.math.BigDecimal getContainerTwoSendNet() {
		return get("container_two_send_net");
	}

	public M setTestIndicators(java.lang.String testIndicators) {
		set("test_indicators", testIndicators);
		return (M)this;
	}
	
	public java.lang.String getTestIndicators() {
		return getStr("test_indicators");
	}

	public M setOrderImg(java.lang.String orderImg) {
		set("order_img", orderImg);
		return (M)this;
	}
	
	public java.lang.String getOrderImg() {
		return getStr("order_img");
	}

	public M setDistributionCargoPlace(java.lang.String distributionCargoPlace) {
		set("distribution_cargo_place", distributionCargoPlace);
		return (M)this;
	}
	
	public java.lang.String getDistributionCargoPlace() {
		return getStr("distribution_cargo_place");
	}

	public M setDistributionCargoSite(java.lang.String distributionCargoSite) {
		set("distribution_cargo_site", distributionCargoSite);
		return (M)this;
	}
	
	public java.lang.String getDistributionCargoSite() {
		return getStr("distribution_cargo_site");
	}

	public M setReceiptTare(java.math.BigDecimal receiptTare) {
		set("receipt_tare", receiptTare);
		return (M)this;
	}
	
	public java.math.BigDecimal getReceiptTare() {
		return get("receipt_tare");
	}

	public M setReceiptGross(java.math.BigDecimal receiptGross) {
		set("receipt_gross", receiptGross);
		return (M)this;
	}
	
	public java.math.BigDecimal getReceiptGross() {
		return get("receipt_gross");
	}

	public M setContainerOneReceiptNet(java.math.BigDecimal containerOneReceiptNet) {
		set("container_one_receipt_net", containerOneReceiptNet);
		return (M)this;
	}
	
	public java.math.BigDecimal getContainerOneReceiptNet() {
		return get("container_one_receipt_net");
	}

	public M setContainerTwoReceiptNet(java.math.BigDecimal containerTwoReceiptNet) {
		set("container_two_receipt_net", containerTwoReceiptNet);
		return (M)this;
	}
	
	public java.math.BigDecimal getContainerTwoReceiptNet() {
		return get("container_two_receipt_net");
	}

	public M setReceiptTestIndicators(java.lang.String receiptTestIndicators) {
		set("receipt_test_indicators", receiptTestIndicators);
		return (M)this;
	}
	
	public java.lang.String getReceiptTestIndicators() {
		return getStr("receipt_test_indicators");
	}

	public M setArriveredImg(java.lang.String arriveredImg) {
		set("arrivered_img", arriveredImg);
		return (M)this;
	}
	
	public java.lang.String getArriveredImg() {
		return getStr("arrivered_img");
	}

	public M setEditDate(java.util.Date editDate) {
		set("edit_date", editDate);
		return (M)this;
	}
	
	public java.util.Date getEditDate() {
		return get("edit_date");
	}

	public M setPieceNumber(java.lang.Integer pieceNumber) {
		set("piece_number", pieceNumber);
		return (M)this;
	}
	
	public java.lang.Integer getPieceNumber() {
		return getInt("piece_number");
	}

	public M setValuationUnitType(java.lang.Integer valuationUnitType) {
		set("valuation_unit_type", valuationUnitType);
		return (M)this;
	}
	
	public java.lang.Integer getValuationUnitType() {
		return getInt("valuation_unit_type");
	}

	public M setCarteamId(java.lang.Integer carteamId) {
		set("carTeam_id", carteamId);
		return (M)this;
	}
	
	public java.lang.Integer getCarteamId() {
		return getInt("carTeam_id");
	}

	public M setPlaceNowId(java.lang.Integer placeNowId) {
		set("place_now_id", placeNowId);
		return (M)this;
	}
	
	public java.lang.Integer getPlaceNowId() {
		return getInt("place_now_id");
	}

	public M setOrderOrigin(java.lang.Integer orderOrigin) {
		set("order_origin", orderOrigin);
		return (M)this;
	}
	
	public java.lang.Integer getOrderOrigin() {
		return getInt("order_origin");
	}

	public M setDeletorId(java.lang.Integer deletorId) {
		set("deletor_id", deletorId);
		return (M)this;
	}
	
	public java.lang.Integer getDeletorId() {
		return getInt("deletor_id");
	}

	public M setDeleteName(java.lang.String deleteName) {
		set("delete_name", deleteName);
		return (M)this;
	}
	
	public java.lang.String getDeleteName() {
		return getStr("delete_name");
	}

	public M setDeleteTime(java.util.Date deleteTime) {
		set("delete_time", deleteTime);
		return (M)this;
	}
	
	public java.util.Date getDeleteTime() {
		return get("delete_time");
	}

	public M setDeleteReason(java.lang.String deleteReason) {
		set("delete_reason", deleteReason);
		return (M)this;
	}
	
	public java.lang.String getDeleteReason() {
		return getStr("delete_reason");
	}

	public M setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.Integer getDeleteFlag() {
		return getInt("delete_flag");
	}

	public M setIsCancel(java.lang.Integer isCancel) {
		set("is_cancel", isCancel);
		return (M)this;
	}
	
	public java.lang.Integer getIsCancel() {
		return getInt("is_cancel");
	}

	public M setCancelReason(java.lang.String cancelReason) {
		set("cancel_reason", cancelReason);
		return (M)this;
	}
	
	public java.lang.String getCancelReason() {
		return getStr("cancel_reason");
	}

	public M setCancelReasonDetail(java.lang.String cancelReasonDetail) {
		set("cancel_reason_detail", cancelReasonDetail);
		return (M)this;
	}
	
	public java.lang.String getCancelReasonDetail() {
		return getStr("cancel_reason_detail");
	}

	public M setCancelDate(java.util.Date cancelDate) {
		set("cancel_date", cancelDate);
		return (M)this;
	}
	
	public java.util.Date getCancelDate() {
		return get("cancel_date");
	}

	public M setReceipterDate(java.util.Date receipterDate) {
		set("receipter_date", receipterDate);
		return (M)this;
	}
	
	public java.util.Date getReceipterDate() {
		return get("receipter_date");
	}

	public M setTakeCargoPlaceId(java.lang.Integer takeCargoPlaceId) {
		set("take_cargo_place_id", takeCargoPlaceId);
		return (M)this;
	}
	
	public java.lang.Integer getTakeCargoPlaceId() {
		return getInt("take_cargo_place_id");
	}

	public M setTakeCarogoPlaceName(java.lang.String takeCarogoPlaceName) {
		set("take_carogo_place_name", takeCarogoPlaceName);
		return (M)this;
	}
	
	public java.lang.String getTakeCarogoPlaceName() {
		return getStr("take_carogo_place_name");
	}

	public M setTakeCargoSiteId(java.lang.Integer takeCargoSiteId) {
		set("take_cargo_site_id", takeCargoSiteId);
		return (M)this;
	}
	
	public java.lang.Integer getTakeCargoSiteId() {
		return getInt("take_cargo_site_id");
	}

	public M setTakeCargoSiteName(java.lang.String takeCargoSiteName) {
		set("take_cargo_site_name", takeCargoSiteName);
		return (M)this;
	}
	
	public java.lang.String getTakeCargoSiteName() {
		return getStr("take_cargo_site_name");
	}

	public M setTakeDeliveryDate(java.util.Date takeDeliveryDate) {
		set("take_delivery_date", takeDeliveryDate);
		return (M)this;
	}
	
	public java.util.Date getTakeDeliveryDate() {
		return get("take_delivery_date");
	}

	public M setDistributionCargoPlaceId(java.lang.Integer distributionCargoPlaceId) {
		set("distribution_cargo_place_id", distributionCargoPlaceId);
		return (M)this;
	}
	
	public java.lang.Integer getDistributionCargoPlaceId() {
		return getInt("distribution_cargo_place_id");
	}

	public M setDistributionCargoSiteId(java.lang.Integer distributionCargoSiteId) {
		set("distribution_cargo_site_id", distributionCargoSiteId);
		return (M)this;
	}
	
	public java.lang.Integer getDistributionCargoSiteId() {
		return getInt("distribution_cargo_site_id");
	}

	public M setCheckcustFlag(java.lang.Integer checkcustFlag) {
		set("checkcust_flag", checkcustFlag);
		return (M)this;
	}
	
	public java.lang.Integer getCheckcustFlag() {
		return getInt("checkcust_flag");
	}

}
