package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbRoadInfo<M extends BaseTbRoadInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setDriverMsg(java.lang.String driverMsg) {
		set("driver_msg", driverMsg);
		return (M)this;
	}
	
	public java.lang.String getDriverMsg() {
		return getStr("driver_msg");
	}

	public M setDriverId(java.lang.String driverId) {
		set("driver_id", driverId);
		return (M)this;
	}
	
	public java.lang.String getDriverId() {
		return getStr("driver_id");
	}

	public M setDriverName(java.lang.String driverName) {
		set("driver_name", driverName);
		return (M)this;
	}
	
	public java.lang.String getDriverName() {
		return getStr("driver_name");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
