package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbShortOrderFinance<M extends BaseTbShortOrderFinance<M>> extends Model<M> implements IBean {

	public M setShOrderFinId(java.lang.String shOrderFinId) {
		set("sh_order_fin_id", shOrderFinId);
		return (M)this;
	}
	
	public java.lang.String getShOrderFinId() {
		return getStr("sh_order_fin_id");
	}

	public M setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
		return (M)this;
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}

	public M setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
		return (M)this;
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public M setFinanceStatus(java.lang.Integer financeStatus) {
		set("finance_status", financeStatus);
		return (M)this;
	}
	
	public java.lang.Integer getFinanceStatus() {
		return getInt("finance_status");
	}

	public M setArrearsItem(java.lang.String arrearsItem) {
		set("arrears_item", arrearsItem);
		return (M)this;
	}
	
	public java.lang.String getArrearsItem() {
		return getStr("arrears_item");
	}

	public M setAddUserId(java.lang.Integer addUserId) {
		set("add_user_id", addUserId);
		return (M)this;
	}
	
	public java.lang.Integer getAddUserId() {
		return getInt("add_user_id");
	}

	public M setAddDate(java.util.Date addDate) {
		set("add_date", addDate);
		return (M)this;
	}
	
	public java.util.Date getAddDate() {
		return get("add_date");
	}

	public M setPackFlag(java.lang.Integer packFlag) {
		set("pack_flag", packFlag);
		return (M)this;
	}
	
	public java.lang.Integer getPackFlag() {
		return getInt("pack_flag");
	}

	public M setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.Integer getDeleteFlag() {
		return getInt("delete_flag");
	}

	public M setShortBargeCost(java.math.BigDecimal shortBargeCost) {
		set("short_barge_cost", shortBargeCost);
		return (M)this;
	}
	
	public java.math.BigDecimal getShortBargeCost() {
		return get("short_barge_cost");
	}

	public M setBuckleFigure(java.math.BigDecimal buckleFigure) {
		set("buckle_figure", buckleFigure);
		return (M)this;
	}
	
	public java.math.BigDecimal getBuckleFigure() {
		return get("buckle_figure");
	}

	public M setSubsidy(java.math.BigDecimal subsidy) {
		set("subsidy", subsidy);
		return (M)this;
	}
	
	public java.math.BigDecimal getSubsidy() {
		return get("subsidy");
	}

	public M setShouldPayFigure(java.math.BigDecimal shouldPayFigure) {
		set("should_pay_figure", shouldPayFigure);
		return (M)this;
	}
	
	public java.math.BigDecimal getShouldPayFigure() {
		return get("should_pay_figure");
	}

	public M setBillingUserId(java.lang.Integer billingUserId) {
		set("billing_user_id", billingUserId);
		return (M)this;
	}
	
	public java.lang.Integer getBillingUserId() {
		return getInt("billing_user_id");
	}

	public M setBillingDate(java.util.Date billingDate) {
		set("billing_date", billingDate);
		return (M)this;
	}
	
	public java.util.Date getBillingDate() {
		return get("billing_date");
	}

	public M setAuditUserId(java.lang.Integer auditUserId) {
		set("audit_user_id", auditUserId);
		return (M)this;
	}
	
	public java.lang.Integer getAuditUserId() {
		return getInt("audit_user_id");
	}

	public M setFinanceAuditDate(java.util.Date financeAuditDate) {
		set("finance_audit_date", financeAuditDate);
		return (M)this;
	}
	
	public java.util.Date getFinanceAuditDate() {
		return get("finance_audit_date");
	}

	public M setCompleteDate(java.util.Date completeDate) {
		set("complete_date", completeDate);
		return (M)this;
	}
	
	public java.util.Date getCompleteDate() {
		return get("complete_date");
	}

	public M setUnusualDate(java.util.Date unusualDate) {
		set("unusual_date", unusualDate);
		return (M)this;
	}
	
	public java.util.Date getUnusualDate() {
		return get("unusual_date");
	}

	public M setUnusualUserId(java.lang.Integer unusualUserId) {
		set("unusual_user_id", unusualUserId);
		return (M)this;
	}
	
	public java.lang.Integer getUnusualUserId() {
		return getInt("unusual_user_id");
	}

	public M setUnusualReason(java.lang.String unusualReason) {
		set("unusual_reason", unusualReason);
		return (M)this;
	}
	
	public java.lang.String getUnusualReason() {
		return getStr("unusual_reason");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setCreateUserId(java.lang.Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}
	
	public java.lang.Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public M setModifiyDate(java.util.Date modifiyDate) {
		set("modifiy_date", modifiyDate);
		return (M)this;
	}
	
	public java.util.Date getModifiyDate() {
		return get("modifiy_date");
	}

}
