package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbDotAccountPack<M extends BaseTbDotAccountPack<M>> extends Model<M> implements IBean {

	public M setDotAccountPackId(java.lang.String dotAccountPackId) {
		set("dot_account_pack_id", dotAccountPackId);
		return (M)this;
	}
	
	public java.lang.String getDotAccountPackId() {
		return getStr("dot_account_pack_id");
	}

	public M setProjectCode(java.lang.String projectCode) {
		set("project_code", projectCode);
		return (M)this;
	}
	
	public java.lang.String getProjectCode() {
		return getStr("project_code");
	}

	public M setBranchName(java.lang.String branchName) {
		set("branch_name", branchName);
		return (M)this;
	}
	
	public java.lang.String getBranchName() {
		return getStr("branch_name");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setPackTruckNum(java.lang.Integer packTruckNum) {
		set("pack_truck_num", packTruckNum);
		return (M)this;
	}
	
	public java.lang.Integer getPackTruckNum() {
		return getInt("pack_truck_num");
	}

	public M setSuppliesAmount(java.math.BigDecimal suppliesAmount) {
		set("supplies_amount", suppliesAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getSuppliesAmount() {
		return get("supplies_amount");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setCreateUserId(java.lang.Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}
	
	public java.lang.Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public M setAuditId(java.lang.Integer auditId) {
		set("audit_id", auditId);
		return (M)this;
	}
	
	public java.lang.Integer getAuditId() {
		return getInt("audit_id");
	}

	public M setAuditDate(java.util.Date auditDate) {
		set("audit_date", auditDate);
		return (M)this;
	}
	
	public java.util.Date getAuditDate() {
		return get("audit_date");
	}

}
