package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbBranchGroupTrainStation<M extends BaseTbBranchGroupTrainStation<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTrainStationId(java.lang.Integer trainStationId) {
		set("train_station_id", trainStationId);
		return (M)this;
	}
	
	public java.lang.Integer getTrainStationId() {
		return getInt("train_station_id");
	}

	public M setBranchGroupId(java.lang.Integer branchGroupId) {
		set("branch_group_id", branchGroupId);
		return (M)this;
	}
	
	public java.lang.Integer getBranchGroupId() {
		return getInt("branch_group_id");
	}

}
