package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbOilGasCard<M extends BaseTbOilGasCard<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setShPackId(java.lang.String shPackId) {
		set("sh_pack_id", shPackId);
		return (M)this;
	}
	
	public java.lang.String getShPackId() {
		return getStr("sh_pack_id");
	}

	public M setOilGasCardsId(java.lang.String oilGasCardsId) {
		set("oil_gas_cards_id", oilGasCardsId);
		return (M)this;
	}
	
	public java.lang.String getOilGasCardsId() {
		return getStr("oil_gas_cards_id");
	}

	public M setCardNum(java.lang.String cardNum) {
		set("card_num", cardNum);
		return (M)this;
	}
	
	public java.lang.String getCardNum() {
		return getStr("card_num");
	}

	public M setCardMoney(java.math.BigDecimal cardMoney) {
		set("card_money", cardMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getCardMoney() {
		return get("card_money");
	}

	public M setCardStatus(java.lang.Integer cardStatus) {
		set("card_status", cardStatus);
		return (M)this;
	}
	
	public java.lang.Integer getCardStatus() {
		return getInt("card_status");
	}

}
