package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbThreePartiesSettle<M extends BaseTbThreePartiesSettle<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setCustPackId(java.lang.String custPackId) {
		set("cust_pack_id", custPackId);
		return (M)this;
	}
	
	public java.lang.String getCustPackId() {
		return getStr("cust_pack_id");
	}

	public M setReceiveAccountId(java.lang.Integer receiveAccountId) {
		set("receive_account_id", receiveAccountId);
		return (M)this;
	}
	
	public java.lang.Integer getReceiveAccountId() {
		return getInt("receive_account_id");
	}

	public M setPayAccountId(java.lang.Integer payAccountId) {
		set("pay_account_id", payAccountId);
		return (M)this;
	}
	
	public java.lang.Integer getPayAccountId() {
		return getInt("pay_account_id");
	}

	public M setSettleMoney(java.math.BigDecimal settleMoney) {
		set("settle_money", settleMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getSettleMoney() {
		return get("settle_money");
	}

	public M setSettleStatus(java.lang.Integer settleStatus) {
		set("settle_status", settleStatus);
		return (M)this;
	}
	
	public java.lang.Integer getSettleStatus() {
		return getInt("settle_status");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}
	
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	public M setAuitBy(java.lang.String auitBy) {
		set("auit_by", auitBy);
		return (M)this;
	}
	
	public java.lang.String getAuitBy() {
		return getStr("auit_by");
	}

	public M setAuitDate(java.util.Date auitDate) {
		set("auit_date", auitDate);
		return (M)this;
	}
	
	public java.util.Date getAuitDate() {
		return get("auit_date");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
		return (M)this;
	}
	
	public java.lang.String getDelFlag() {
		return getStr("del_flag");
	}

	public M setThreePartiesReceivablesId(java.lang.String threePartiesReceivablesId) {
		set("three_parties_receivables_id", threePartiesReceivablesId);
		return (M)this;
	}
	
	public java.lang.String getThreePartiesReceivablesId() {
		return getStr("three_parties_receivables_id");
	}

}
