package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbProjectDistribution<M extends BaseTbProjectDistribution<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
		return (M)this;
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}

	public M setProjectCode(java.lang.String projectCode) {
		set("project_code", projectCode);
		return (M)this;
	}
	
	public java.lang.String getProjectCode() {
		return getStr("project_code");
	}

	public M setProjectType(java.lang.Integer projectType) {
		set("project_type", projectType);
		return (M)this;
	}
	
	public java.lang.Integer getProjectType() {
		return getInt("project_type");
	}

	public M setTransportType(java.lang.Integer transportType) {
		set("transport_type", transportType);
		return (M)this;
	}
	
	public java.lang.Integer getTransportType() {
		return getInt("transport_type");
	}

	public M setSendCompanyId(java.lang.Integer sendCompanyId) {
		set("send_company_id", sendCompanyId);
		return (M)this;
	}
	
	public java.lang.Integer getSendCompanyId() {
		return getInt("send_company_id");
	}

	public M setReceiveCompanyId(java.lang.Integer receiveCompanyId) {
		set("receive_company_id", receiveCompanyId);
		return (M)this;
	}
	
	public java.lang.Integer getReceiveCompanyId() {
		return getInt("receive_company_id");
	}

	public M setCarNum(java.lang.Integer carNum) {
		set("car_num", carNum);
		return (M)this;
	}
	
	public java.lang.Integer getCarNum() {
		return getInt("car_num");
	}

	public M setSingleWeight(java.math.BigDecimal singleWeight) {
		set("single_weight", singleWeight);
		return (M)this;
	}
	
	public java.math.BigDecimal getSingleWeight() {
		return get("single_weight");
	}

	public M setCreatorId(java.lang.Integer creatorId) {
		set("creator_id", creatorId);
		return (M)this;
	}
	
	public java.lang.Integer getCreatorId() {
		return getInt("creator_id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setExpireDate(java.util.Date expireDate) {
		set("expire_date", expireDate);
		return (M)this;
	}
	
	public java.util.Date getExpireDate() {
		return get("expire_date");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setAlreadyRecNum(java.lang.Integer alreadyRecNum) {
		set("already_rec_num", alreadyRecNum);
		return (M)this;
	}
	
	public java.lang.Integer getAlreadyRecNum() {
		return getInt("already_rec_num");
	}

	public M setCompleteNum(java.lang.Integer completeNum) {
		set("complete_num", completeNum);
		return (M)this;
	}
	
	public java.lang.Integer getCompleteNum() {
		return getInt("complete_num");
	}

	public M setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.Integer getDeleteFlag() {
		return getInt("delete_flag");
	}

	public M setOverFlag(java.lang.Integer overFlag) {
		set("over_flag", overFlag);
		return (M)this;
	}
	
	public java.lang.Integer getOverFlag() {
		return getInt("over_flag");
	}

}
