package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbStockCharging<M extends BaseTbStockCharging<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
		return (M)this;
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}

	public M setSite(java.lang.String site) {
		set("site", site);
		return (M)this;
	}
	
	public java.lang.String getSite() {
		return getStr("site");
	}

	public M setFreightYardId(java.lang.Integer freightYardId) {
		set("freight_yard_id", freightYardId);
		return (M)this;
	}
	
	public java.lang.Integer getFreightYardId() {
		return getInt("freight_yard_id");
	}

	public M setLocationId(java.lang.Integer locationId) {
		set("location_id", locationId);
		return (M)this;
	}
	
	public java.lang.Integer getLocationId() {
		return getInt("location_id");
	}

	public M setChargingType(java.lang.String chargingType) {
		set("charging_type", chargingType);
		return (M)this;
	}
	
	public java.lang.String getChargingType() {
		return getStr("charging_type");
	}

	public M setDeductionPayId(java.lang.Integer deductionPayId) {
		set("deduction_pay_id", deductionPayId);
		return (M)this;
	}
	
	public java.lang.Integer getDeductionPayId() {
		return getInt("deduction_pay_id");
	}

	public M setDeductionPayName(java.lang.String deductionPayName) {
		set("deduction_pay_name", deductionPayName);
		return (M)this;
	}
	
	public java.lang.String getDeductionPayName() {
		return getStr("deduction_pay_name");
	}

	public M setChargingTonnage(java.lang.Float chargingTonnage) {
		set("charging_tonnage", chargingTonnage);
		return (M)this;
	}
	
	public java.lang.Float getChargingTonnage() {
		return getFloat("charging_tonnage");
	}

	public M setChargingTimeType(java.lang.Integer chargingTimeType) {
		set("charging_time_type", chargingTimeType);
		return (M)this;
	}
	
	public java.lang.Integer getChargingTimeType() {
		return getInt("charging_time_type");
	}

	public M setUnitPay(java.math.BigDecimal unitPay) {
		set("unit_pay", unitPay);
		return (M)this;
	}
	
	public java.math.BigDecimal getUnitPay() {
		return get("unit_pay");
	}

	public M setLateFee(java.math.BigDecimal lateFee) {
		set("late_fee", lateFee);
		return (M)this;
	}
	
	public java.math.BigDecimal getLateFee() {
		return get("late_fee");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setOperatorId(java.lang.Integer operatorId) {
		set("operator_id", operatorId);
		return (M)this;
	}
	
	public java.lang.Integer getOperatorId() {
		return getInt("operator_id");
	}

	public M setOperateTime(java.util.Date operateTime) {
		set("operate_time", operateTime);
		return (M)this;
	}
	
	public java.util.Date getOperateTime() {
		return get("operate_time");
	}

}
