package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbStationBusiness<M extends BaseTbStationBusiness<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setRelateId(java.lang.Integer relateId) {
		set("relate_id", relateId);
		return (M)this;
	}
	
	public java.lang.Integer getRelateId() {
		return getInt("relate_id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setDepartment(java.lang.String department) {
		set("department", department);
		return (M)this;
	}
	
	public java.lang.String getDepartment() {
		return getStr("department");
	}

	public M setJob(java.lang.String job) {
		set("job", job);
		return (M)this;
	}
	
	public java.lang.String getJob() {
		return getStr("job");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setRelateProjectId(java.lang.Integer relateProjectId) {
		set("relate_project_id", relateProjectId);
		return (M)this;
	}
	
	public java.lang.Integer getRelateProjectId() {
		return getInt("relate_project_id");
	}

	public M setRelateProjectCode(java.lang.String relateProjectCode) {
		set("relate_project_code", relateProjectCode);
		return (M)this;
	}
	
	public java.lang.String getRelateProjectCode() {
		return getStr("relate_project_code");
	}

	public M setAreaCode(java.lang.String areaCode) {
		set("area_code", areaCode);
		return (M)this;
	}
	
	public java.lang.String getAreaCode() {
		return getStr("area_code");
	}

	public M setLocation(java.lang.String location) {
		set("location", location);
		return (M)this;
	}
	
	public java.lang.String getLocation() {
		return getStr("location");
	}

	public M setStage(java.lang.Integer stage) {
		set("stage", stage);
		return (M)this;
	}
	
	public java.lang.Integer getStage() {
		return getInt("stage");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
