package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbCostPack<M extends BaseTbCostPack<M>> extends Model<M> implements IBean {

	public M setShPackId(java.lang.String shPackId) {
		set("sh_pack_id", shPackId);
		return (M)this;
	}
	
	public java.lang.String getShPackId() {
		return getStr("sh_pack_id");
	}

	public M setCostPackCode(java.lang.String costPackCode) {
		set("cost_pack_code", costPackCode);
		return (M)this;
	}
	
	public java.lang.String getCostPackCode() {
		return getStr("cost_pack_code");
	}

	public M setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
		return (M)this;
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}

	public M setCheckingStatus(java.lang.Integer checkingStatus) {
		set("checking_status", checkingStatus);
		return (M)this;
	}
	
	public java.lang.Integer getCheckingStatus() {
		return getInt("checking_status");
	}

	public M setCashSettleStatus(java.lang.Integer cashSettleStatus) {
		set("cash_settle_status", cashSettleStatus);
		return (M)this;
	}
	
	public java.lang.Integer getCashSettleStatus() {
		return getInt("cash_settle_status");
	}

	public M setInvoiceStatus(java.lang.Integer invoiceStatus) {
		set("invoice_status", invoiceStatus);
		return (M)this;
	}
	
	public java.lang.Integer getInvoiceStatus() {
		return getInt("invoice_status");
	}

	public M setPackTruckNum(java.lang.Integer packTruckNum) {
		set("pack_truck_num", packTruckNum);
		return (M)this;
	}
	
	public java.lang.Integer getPackTruckNum() {
		return getInt("pack_truck_num");
	}

	public M setSendTare(java.math.BigDecimal sendTare) {
		set("send_tare", sendTare);
		return (M)this;
	}
	
	public java.math.BigDecimal getSendTare() {
		return get("send_tare");
	}

	public M setSendGross(java.math.BigDecimal sendGross) {
		set("send_gross", sendGross);
		return (M)this;
	}
	
	public java.math.BigDecimal getSendGross() {
		return get("send_gross");
	}

	public M setTaxRate(java.math.BigDecimal taxRate) {
		set("tax_rate", taxRate);
		return (M)this;
	}
	
	public java.math.BigDecimal getTaxRate() {
		return get("tax_rate");
	}

	public M setSendNet(java.math.BigDecimal sendNet) {
		set("send_net", sendNet);
		return (M)this;
	}
	
	public java.math.BigDecimal getSendNet() {
		return get("send_net");
	}

	public M setCargoPrice(java.math.BigDecimal cargoPrice) {
		set("cargo_price", cargoPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getCargoPrice() {
		return get("cargo_price");
	}

	public M setCargoUnitPrice(java.math.BigDecimal cargoUnitPrice) {
		set("cargo_unit_price", cargoUnitPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getCargoUnitPrice() {
		return get("cargo_unit_price");
	}

	public M setCashPayType(java.lang.Integer cashPayType) {
		set("cash_pay_type", cashPayType);
		return (M)this;
	}
	
	public java.lang.Integer getCashPayType() {
		return getInt("cash_pay_type");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.Integer getDeleteFlag() {
		return getInt("delete_flag");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setCreateUserId(java.lang.Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}
	
	public java.lang.Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public M setModifiyDate(java.util.Date modifiyDate) {
		set("modifiy_date", modifiyDate);
		return (M)this;
	}
	
	public java.util.Date getModifiyDate() {
		return get("modifiy_date");
	}

	public M setCheckingAuditDate(java.util.Date checkingAuditDate) {
		set("checking_audit_date", checkingAuditDate);
		return (M)this;
	}
	
	public java.util.Date getCheckingAuditDate() {
		return get("checking_audit_date");
	}

	public M setSettleAuditDate(java.util.Date settleAuditDate) {
		set("settle_audit_date", settleAuditDate);
		return (M)this;
	}
	
	public java.util.Date getSettleAuditDate() {
		return get("settle_audit_date");
	}

	public M setAuditId(java.lang.Integer auditId) {
		set("audit_id", auditId);
		return (M)this;
	}
	
	public java.lang.Integer getAuditId() {
		return getInt("audit_id");
	}

	public M setBackId(java.lang.Integer backId) {
		set("back_id", backId);
		return (M)this;
	}
	
	public java.lang.Integer getBackId() {
		return getInt("back_id");
	}

	public M setBackDate(java.util.Date backDate) {
		set("back_date", backDate);
		return (M)this;
	}
	
	public java.util.Date getBackDate() {
		return get("back_date");
	}

	public M setTaxMoney(java.math.BigDecimal taxMoney) {
		set("tax_money", taxMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getTaxMoney() {
		return get("tax_money");
	}

	public M setBesettledMoney(java.math.BigDecimal besettledMoney) {
		set("besettled_money", besettledMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getBesettledMoney() {
		return get("besettled_money");
	}

	public M setSettledMoney(java.math.BigDecimal settledMoney) {
		set("settled_money", settledMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getSettledMoney() {
		return get("settled_money");
	}

	public M setSettleMoney(java.math.BigDecimal settleMoney) {
		set("settle_money", settleMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getSettleMoney() {
		return get("settle_money");
	}

	public M setSettleType(java.lang.Integer settleType) {
		set("settle_type", settleType);
		return (M)this;
	}
	
	public java.lang.Integer getSettleType() {
		return getInt("settle_type");
	}

	public M setSettleDate(java.util.Date settleDate) {
		set("settle_date", settleDate);
		return (M)this;
	}
	
	public java.util.Date getSettleDate() {
		return get("settle_date");
	}

	public M setSettleId(java.lang.String settleId) {
		set("settle_id", settleId);
		return (M)this;
	}
	
	public java.lang.String getSettleId() {
		return getStr("settle_id");
	}

	public M setSettleAuditUid(java.lang.Integer settleAuditUid) {
		set("settle_audit_uid", settleAuditUid);
		return (M)this;
	}
	
	public java.lang.Integer getSettleAuditUid() {
		return getInt("settle_audit_uid");
	}

	public M setIsHistroy(java.lang.Integer isHistroy) {
		set("is_histroy", isHistroy);
		return (M)this;
	}
	
	public java.lang.Integer getIsHistroy() {
		return getInt("is_histroy");
	}

	public M setReceiveAccountId(java.lang.Integer receiveAccountId) {
		set("receive_account_id", receiveAccountId);
		return (M)this;
	}
	
	public java.lang.Integer getReceiveAccountId() {
		return getInt("receive_account_id");
	}

}
