package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbProject<M extends BaseTbProject<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setProjectCode(java.lang.String projectCode) {
		set("project_code", projectCode);
		return (M)this;
	}
	
	public java.lang.String getProjectCode() {
		return getStr("project_code");
	}

	public M setBranchGroupId(java.lang.Integer branchGroupId) {
		set("branch_group_id", branchGroupId);
		return (M)this;
	}
	
	public java.lang.Integer getBranchGroupId() {
		return getInt("branch_group_id");
	}

	public M setBranchGroupName(java.lang.String branchGroupName) {
		set("branch_group_name", branchGroupName);
		return (M)this;
	}
	
	public java.lang.String getBranchGroupName() {
		return getStr("branch_group_name");
	}

	public M setProjectType(java.lang.Integer projectType) {
		set("project_type", projectType);
		return (M)this;
	}
	
	public java.lang.Integer getProjectType() {
		return getInt("project_type");
	}

	public M setTransportType(java.lang.Integer transportType) {
		set("transport_type", transportType);
		return (M)this;
	}
	
	public java.lang.Integer getTransportType() {
		return getInt("transport_type");
	}

	public M setCargoId(java.lang.Integer cargoId) {
		set("cargo_id", cargoId);
		return (M)this;
	}
	
	public java.lang.Integer getCargoId() {
		return getInt("cargo_id");
	}

	public M setCargoName(java.lang.String cargoName) {
		set("cargo_name", cargoName);
		return (M)this;
	}
	
	public java.lang.String getCargoName() {
		return getStr("cargo_name");
	}

	public M setCargoSpecifications(java.lang.String cargoSpecifications) {
		set("cargo_specifications", cargoSpecifications);
		return (M)this;
	}
	
	public java.lang.String getCargoSpecifications() {
		return getStr("cargo_specifications");
	}

	public M setCargoPrice(java.math.BigDecimal cargoPrice) {
		set("cargo_price", cargoPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getCargoPrice() {
		return get("cargo_price");
	}

	public M setValuationUnitName(java.lang.Integer valuationUnitName) {
		set("valuation_unit_name", valuationUnitName);
		return (M)this;
	}
	
	public java.lang.Integer getValuationUnitName() {
		return getInt("valuation_unit_name");
	}

	public M setSendCargoCompanyId(java.lang.Integer sendCargoCompanyId) {
		set("send_cargo_company_id", sendCargoCompanyId);
		return (M)this;
	}
	
	public java.lang.Integer getSendCargoCompanyId() {
		return getInt("send_cargo_company_id");
	}

	public M setSendCargoCompanyName(java.lang.String sendCargoCompanyName) {
		set("send_cargo_company_name", sendCargoCompanyName);
		return (M)this;
	}
	
	public java.lang.String getSendCargoCompanyName() {
		return getStr("send_cargo_company_name");
	}

	public M setReceiveCargoCompanyId(java.lang.Integer receiveCargoCompanyId) {
		set("receive_cargo_company_id", receiveCargoCompanyId);
		return (M)this;
	}
	
	public java.lang.Integer getReceiveCargoCompanyId() {
		return getInt("receive_cargo_company_id");
	}

	public M setReceiveCargoCompanyName(java.lang.String receiveCargoCompanyName) {
		set("receive_cargo_company_name", receiveCargoCompanyName);
		return (M)this;
	}
	
	public java.lang.String getReceiveCargoCompanyName() {
		return getStr("receive_cargo_company_name");
	}

	public M setSendCargoUnitId(java.lang.Integer sendCargoUnitId) {
		set("send_cargo_unit_id", sendCargoUnitId);
		return (M)this;
	}
	
	public java.lang.Integer getSendCargoUnitId() {
		return getInt("send_cargo_unit_id");
	}

	public M setSendCargoUnitName(java.lang.String sendCargoUnitName) {
		set("send_cargo_unit_name", sendCargoUnitName);
		return (M)this;
	}
	
	public java.lang.String getSendCargoUnitName() {
		return getStr("send_cargo_unit_name");
	}

	public M setReceiveCargoSiteId(java.lang.Integer receiveCargoSiteId) {
		set("receive_cargo_site_id", receiveCargoSiteId);
		return (M)this;
	}
	
	public java.lang.Integer getReceiveCargoSiteId() {
		return getInt("receive_cargo_site_id");
	}

	public M setReceiveCargoSite(java.lang.String receiveCargoSite) {
		set("receive_cargo_site", receiveCargoSite);
		return (M)this;
	}
	
	public java.lang.String getReceiveCargoSite() {
		return getStr("receive_cargo_site");
	}

	public M setReceiveCenterCargoSiteId(java.lang.Integer receiveCenterCargoSiteId) {
		set("receive_center_cargo_site_id", receiveCenterCargoSiteId);
		return (M)this;
	}
	
	public java.lang.Integer getReceiveCenterCargoSiteId() {
		return getInt("receive_center_cargo_site_id");
	}

	public M setReceiveCargoSiteFreightYardId(java.lang.Integer receiveCargoSiteFreightYardId) {
		set("receive_cargo_site_freight_yard_id", receiveCargoSiteFreightYardId);
		return (M)this;
	}
	
	public java.lang.Integer getReceiveCargoSiteFreightYardId() {
		return getInt("receive_cargo_site_freight_yard_id");
	}

	public M setShortBargeCarrierMode(java.lang.Integer shortBargeCarrierMode) {
		set("short_barge_carrier_mode", shortBargeCarrierMode);
		return (M)this;
	}
	
	public java.lang.Integer getShortBargeCarrierMode() {
		return getInt("short_barge_carrier_mode");
	}

	public M setShortBargeCarrierId(java.lang.Integer shortBargeCarrierId) {
		set("short_barge_carrier_id", shortBargeCarrierId);
		return (M)this;
	}
	
	public java.lang.Integer getShortBargeCarrierId() {
		return getInt("short_barge_carrier_id");
	}

	public M setShortBargeCarrierName(java.lang.String shortBargeCarrierName) {
		set("short_barge_carrier_name", shortBargeCarrierName);
		return (M)this;
	}
	
	public java.lang.String getShortBargeCarrierName() {
		return getStr("short_barge_carrier_name");
	}

	public M setSendShortBargeCarrierMode(java.lang.Integer sendShortBargeCarrierMode) {
		set("send_short_barge_carrier_mode", sendShortBargeCarrierMode);
		return (M)this;
	}
	
	public java.lang.Integer getSendShortBargeCarrierMode() {
		return getInt("send_short_barge_carrier_mode");
	}

	public M setBeginCenterSiteId(java.lang.Integer beginCenterSiteId) {
		set("begin_center_site_id", beginCenterSiteId);
		return (M)this;
	}
	
	public java.lang.Integer getBeginCenterSiteId() {
		return getInt("begin_center_site_id");
	}

	public M setBeginCenterSiteName(java.lang.String beginCenterSiteName) {
		set("begin_center_site_name", beginCenterSiteName);
		return (M)this;
	}
	
	public java.lang.String getBeginCenterSiteName() {
		return getStr("begin_center_site_name");
	}

	public M setBeginSiteId(java.lang.Integer beginSiteId) {
		set("begin_site_id", beginSiteId);
		return (M)this;
	}
	
	public java.lang.Integer getBeginSiteId() {
		return getInt("begin_site_id");
	}

	public M setBeginSiteName(java.lang.String beginSiteName) {
		set("begin_site_name", beginSiteName);
		return (M)this;
	}
	
	public java.lang.String getBeginSiteName() {
		return getStr("begin_site_name");
	}

	public M setBeginSiteFreightYard(java.lang.String beginSiteFreightYard) {
		set("begin_site_freight_yard", beginSiteFreightYard);
		return (M)this;
	}
	
	public java.lang.String getBeginSiteFreightYard() {
		return getStr("begin_site_freight_yard");
	}

	public M setEndCenterSiteId(java.lang.Integer endCenterSiteId) {
		set("end_center_site_id", endCenterSiteId);
		return (M)this;
	}
	
	public java.lang.Integer getEndCenterSiteId() {
		return getInt("end_center_site_id");
	}

	public M setBeginAddress(java.lang.String beginAddress) {
		set("begin_address", beginAddress);
		return (M)this;
	}
	
	public java.lang.String getBeginAddress() {
		return getStr("begin_address");
	}

	public M setEndCenterSiteName(java.lang.String endCenterSiteName) {
		set("end_center_site_name", endCenterSiteName);
		return (M)this;
	}
	
	public java.lang.String getEndCenterSiteName() {
		return getStr("end_center_site_name");
	}

	public M setEndSiteId(java.lang.Integer endSiteId) {
		set("end_site_id", endSiteId);
		return (M)this;
	}
	
	public java.lang.Integer getEndSiteId() {
		return getInt("end_site_id");
	}

	public M setEndSiteName(java.lang.String endSiteName) {
		set("end_site_name", endSiteName);
		return (M)this;
	}
	
	public java.lang.String getEndSiteName() {
		return getStr("end_site_name");
	}

	public M setEndSiteFreightYard(java.lang.String endSiteFreightYard) {
		set("end_site_freight_yard", endSiteFreightYard);
		return (M)this;
	}
	
	public java.lang.String getEndSiteFreightYard() {
		return getStr("end_site_freight_yard");
	}

	public M setEndAddress(java.lang.String endAddress) {
		set("end_address", endAddress);
		return (M)this;
	}
	
	public java.lang.String getEndAddress() {
		return getStr("end_address");
	}

	public M setFreight(java.math.BigDecimal freight) {
		set("freight", freight);
		return (M)this;
	}
	
	public java.math.BigDecimal getFreight() {
		return get("freight");
	}

	public M setMaterialCost(java.math.BigDecimal materialCost) {
		set("material_cost", materialCost);
		return (M)this;
	}
	
	public java.math.BigDecimal getMaterialCost() {
		return get("material_cost");
	}

	public M setTarpaulinCost(java.math.BigDecimal tarpaulinCost) {
		set("tarpaulin_cost", tarpaulinCost);
		return (M)this;
	}
	
	public java.math.BigDecimal getTarpaulinCost() {
		return get("tarpaulin_cost");
	}

	public M setBeginStevedoringCost(java.math.BigDecimal beginStevedoringCost) {
		set("begin_stevedoring_cost", beginStevedoringCost);
		return (M)this;
	}
	
	public java.math.BigDecimal getBeginStevedoringCost() {
		return get("begin_stevedoring_cost");
	}

	public M setEndStevedoringCost(java.math.BigDecimal endStevedoringCost) {
		set("end_stevedoring_cost", endStevedoringCost);
		return (M)this;
	}
	
	public java.math.BigDecimal getEndStevedoringCost() {
		return get("end_stevedoring_cost");
	}

	public M setFreightSum(java.math.BigDecimal freightSum) {
		set("freight_sum", freightSum);
		return (M)this;
	}
	
	public java.math.BigDecimal getFreightSum() {
		return get("freight_sum");
	}

	public M setForwardingSiteId(java.lang.Integer forwardingSiteId) {
		set("forwarding_site_id", forwardingSiteId);
		return (M)this;
	}
	
	public java.lang.Integer getForwardingSiteId() {
		return getInt("forwarding_site_id");
	}

	public M setForwardingSiteName(java.lang.String forwardingSiteName) {
		set("forwarding_site_name", forwardingSiteName);
		return (M)this;
	}
	
	public java.lang.String getForwardingSiteName() {
		return getStr("forwarding_site_name");
	}

	public M setForwardingCenterSiteId(java.lang.Integer forwardingCenterSiteId) {
		set("forwarding_center_site_id", forwardingCenterSiteId);
		return (M)this;
	}
	
	public java.lang.Integer getForwardingCenterSiteId() {
		return getInt("forwarding_center_site_id");
	}

	public M setForwardingSiteFreightYardId(java.lang.Integer forwardingSiteFreightYardId) {
		set("forwarding_site_freight_yard_id", forwardingSiteFreightYardId);
		return (M)this;
	}
	
	public java.lang.Integer getForwardingSiteFreightYardId() {
		return getInt("forwarding_site_freight_yard_id");
	}

	public M setForwardingUnitId(java.lang.Integer forwardingUnitId) {
		set("forwarding_unit_id", forwardingUnitId);
		return (M)this;
	}
	
	public java.lang.Integer getForwardingUnitId() {
		return getInt("forwarding_unit_id");
	}

	public M setForwardingUnitName(java.lang.String forwardingUnitName) {
		set("forwarding_unit_name", forwardingUnitName);
		return (M)this;
	}
	
	public java.lang.String getForwardingUnitName() {
		return getStr("forwarding_unit_name");
	}

	public M setTakePlace(java.lang.String takePlace) {
		set("take_place", takePlace);
		return (M)this;
	}
	
	public java.lang.String getTakePlace() {
		return getStr("take_place");
	}

	public M setTakePlaceDetail(java.lang.String takePlaceDetail) {
		set("take_place_detail", takePlaceDetail);
		return (M)this;
	}
	
	public java.lang.String getTakePlaceDetail() {
		return getStr("take_place_detail");
	}

	public M setReceivingDepartmentId(java.lang.Integer receivingDepartmentId) {
		set("receiving_department_id", receivingDepartmentId);
		return (M)this;
	}
	
	public java.lang.Integer getReceivingDepartmentId() {
		return getInt("receiving_department_id");
	}

	public M setReceivingDepartmentName(java.lang.String receivingDepartmentName) {
		set("receiving_department_name", receivingDepartmentName);
		return (M)this;
	}
	
	public java.lang.String getReceivingDepartmentName() {
		return getStr("receiving_department_name");
	}

	public M setArrivePlace(java.lang.String arrivePlace) {
		set("arrive_place", arrivePlace);
		return (M)this;
	}
	
	public java.lang.String getArrivePlace() {
		return getStr("arrive_place");
	}

	public M setArrivePlaceAddress(java.lang.String arrivePlaceAddress) {
		set("arrive_place_address", arrivePlaceAddress);
		return (M)this;
	}
	
	public java.lang.String getArrivePlaceAddress() {
		return getStr("arrive_place_address");
	}

	public M setPickUpPrice(java.math.BigDecimal pickUpPrice) {
		set("pick_up_price", pickUpPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getPickUpPrice() {
		return get("pick_up_price");
	}

	public M setTrainPrice(java.math.BigDecimal trainPrice) {
		set("train_price", trainPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getTrainPrice() {
		return get("train_price");
	}

	public M setArrivePrice(java.math.BigDecimal arrivePrice) {
		set("arrive_price", arrivePrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getArrivePrice() {
		return get("arrive_price");
	}

	public M setTransportPrice(java.math.BigDecimal transportPrice) {
		set("transport_price", transportPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getTransportPrice() {
		return get("transport_price");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setProjectDistributionId(java.lang.Integer projectDistributionId) {
		set("project_distribution_id", projectDistributionId);
		return (M)this;
	}
	
	public java.lang.Integer getProjectDistributionId() {
		return getInt("project_distribution_id");
	}

	public M setEditDate(java.util.Date editDate) {
		set("edit_date", editDate);
		return (M)this;
	}
	
	public java.util.Date getEditDate() {
		return get("edit_date");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setCreatorId(java.lang.Integer creatorId) {
		set("creator_id", creatorId);
		return (M)this;
	}
	
	public java.lang.Integer getCreatorId() {
		return getInt("creator_id");
	}

	public M setPrincipal(java.lang.Integer principal) {
		set("principal", principal);
		return (M)this;
	}
	
	public java.lang.Integer getPrincipal() {
		return getInt("principal");
	}

	public M setIs_distribution(java.lang.Integer is_distribution) {
		set("is__distribution", is_distribution);
		return (M)this;
	}
	
	public java.lang.Integer getIs_distribution() {
		return getInt("is__distribution");
	}

	public M setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.Integer getDeleteFlag() {
		return getInt("delete_flag");
	}

	public M setFinishDate(java.util.Date finishDate) {
		set("finish_date", finishDate);
		return (M)this;
	}
	
	public java.util.Date getFinishDate() {
		return get("finish_date");
	}

}
