package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbDictItem<M extends BaseTbDictItem<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setDicId(java.lang.String dicId) {
		set("dic_id", dicId);
		return (M)this;
	}
	
	public java.lang.String getDicId() {
		return getStr("dic_id");
	}

	public M setItemCode(java.lang.String itemCode) {
		set("item_code", itemCode);
		return (M)this;
	}
	
	public java.lang.String getItemCode() {
		return getStr("item_code");
	}

	public M setItemName(java.lang.String itemName) {
		set("item_name", itemName);
		return (M)this;
	}
	
	public java.lang.String getItemName() {
		return getStr("item_name");
	}

	public M setItemSort(java.lang.String itemSort) {
		set("item_sort", itemSort);
		return (M)this;
	}
	
	public java.lang.String getItemSort() {
		return getStr("item_sort");
	}

}
