package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbTrainOrderCargoPalce<M extends BaseTbTrainOrderCargoPalce<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTrainOrderId(java.lang.Integer trainOrderId) {
		set("train_order_id", trainOrderId);
		return (M)this;
	}
	
	public java.lang.Integer getTrainOrderId() {
		return getInt("train_order_id");
	}

	public M setCargoPlaceId(java.lang.Integer cargoPlaceId) {
		set("cargo_place_id", cargoPlaceId);
		return (M)this;
	}
	
	public java.lang.Integer getCargoPlaceId() {
		return getInt("cargo_place_id");
	}

	public M setCargoPlaceName(java.lang.String cargoPlaceName) {
		set("cargo_place_name", cargoPlaceName);
		return (M)this;
	}
	
	public java.lang.String getCargoPlaceName() {
		return getStr("cargo_place_name");
	}

	public M setCargoSiteId(java.lang.Integer cargoSiteId) {
		set("cargo_site_id", cargoSiteId);
		return (M)this;
	}
	
	public java.lang.Integer getCargoSiteId() {
		return getInt("cargo_site_id");
	}

	public M setCargoSiteName(java.lang.String cargoSiteName) {
		set("cargo_site_name", cargoSiteName);
		return (M)this;
	}
	
	public java.lang.String getCargoSiteName() {
		return getStr("cargo_site_name");
	}

	public M setCarTypeId(java.lang.Integer carTypeId) {
		set("car_type_id", carTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getCarTypeId() {
		return getInt("car_type_id");
	}

	public M setCarType(java.lang.String carType) {
		set("car_type", carType);
		return (M)this;
	}
	
	public java.lang.String getCarType() {
		return getStr("car_type");
	}

	public M setCarNumber(java.lang.String carNumber) {
		set("car_number", carNumber);
		return (M)this;
	}
	
	public java.lang.String getCarNumber() {
		return getStr("car_number");
	}

	public M setContainerNumber1(java.lang.String containerNumber1) {
		set("container_number1", containerNumber1);
		return (M)this;
	}
	
	public java.lang.String getContainerNumber1() {
		return getStr("container_number1");
	}

	public M setContainerNumber2(java.lang.String containerNumber2) {
		set("container_number2", containerNumber2);
		return (M)this;
	}
	
	public java.lang.String getContainerNumber2() {
		return getStr("container_number2");
	}

	public M setSendWeight(java.math.BigDecimal sendWeight) {
		set("send_weight", sendWeight);
		return (M)this;
	}
	
	public java.math.BigDecimal getSendWeight() {
		return get("send_weight");
	}

	public M setConSendWeight2(java.math.BigDecimal conSendWeight2) {
		set("con_send_weight2", conSendWeight2);
		return (M)this;
	}
	
	public java.math.BigDecimal getConSendWeight2() {
		return get("con_send_weight2");
	}

	public M setUnloadWeight(java.math.BigDecimal unloadWeight) {
		set("unload_weight", unloadWeight);
		return (M)this;
	}
	
	public java.math.BigDecimal getUnloadWeight() {
		return get("unload_weight");
	}

	public M setConUnloadWeight2(java.math.BigDecimal conUnloadWeight2) {
		set("con_unload_weight2", conUnloadWeight2);
		return (M)this;
	}
	
	public java.math.BigDecimal getConUnloadWeight2() {
		return get("con_unload_weight2");
	}

	public M setSendImg(java.lang.String sendImg) {
		set("send_img", sendImg);
		return (M)this;
	}
	
	public java.lang.String getSendImg() {
		return getStr("send_img");
	}

	public M setUnloadImg(java.lang.String unloadImg) {
		set("unload_img", unloadImg);
		return (M)this;
	}
	
	public java.lang.String getUnloadImg() {
		return getStr("unload_img");
	}

	public M setArriveCargoPlaceId(java.lang.Integer arriveCargoPlaceId) {
		set("arrive_cargo_place_id", arriveCargoPlaceId);
		return (M)this;
	}
	
	public java.lang.Integer getArriveCargoPlaceId() {
		return getInt("arrive_cargo_place_id");
	}

	public M setArriveCargoPlaceName(java.lang.String arriveCargoPlaceName) {
		set("arrive_cargo_place_name", arriveCargoPlaceName);
		return (M)this;
	}
	
	public java.lang.String getArriveCargoPlaceName() {
		return getStr("arrive_cargo_place_name");
	}

	public M setArriveCargoSiteId(java.lang.Integer arriveCargoSiteId) {
		set("arrive_cargo_site_id", arriveCargoSiteId);
		return (M)this;
	}
	
	public java.lang.Integer getArriveCargoSiteId() {
		return getInt("arrive_cargo_site_id");
	}

	public M setArriveCargoSiteName(java.lang.String arriveCargoSiteName) {
		set("arrive_cargo_site_name", arriveCargoSiteName);
		return (M)this;
	}
	
	public java.lang.String getArriveCargoSiteName() {
		return getStr("arrive_cargo_site_name");
	}

	public M setArriveUnloadTime(java.util.Date arriveUnloadTime) {
		set("arrive_unload_time", arriveUnloadTime);
		return (M)this;
	}
	
	public java.util.Date getArriveUnloadTime() {
		return get("arrive_unload_time");
	}

	public M setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.Integer getDeleteFlag() {
		return getInt("delete_flag");
	}

}
