package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbCustomerPackOrder<M extends BaseTbCustomerPackOrder<M>> extends Model<M> implements IBean {

	public M setCustPackOrderId(java.lang.String custPackOrderId) {
		set("cust_pack_order_id", custPackOrderId);
		return (M)this;
	}
	
	public java.lang.String getCustPackOrderId() {
		return getStr("cust_pack_order_id");
	}

	public M setCustPackId(java.lang.String custPackId) {
		set("cust_pack_id", custPackId);
		return (M)this;
	}
	
	public java.lang.String getCustPackId() {
		return getStr("cust_pack_id");
	}

	public M setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
		return (M)this;
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public M setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.Integer getDeleteFlag() {
		return getInt("delete_flag");
	}

}
