package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbMaterial<M extends BaseTbMaterial<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setSalesUnit(java.lang.String salesUnit) {
		set("sales_unit", salesUnit);
		return (M)this;
	}
	
	public java.lang.String getSalesUnit() {
		return getStr("sales_unit");
	}

	public M setBranchGroupId(java.lang.Integer branchGroupId) {
		set("branch_group_id", branchGroupId);
		return (M)this;
	}
	
	public java.lang.Integer getBranchGroupId() {
		return getInt("branch_group_id");
	}

	public M setMaterialName(java.lang.String materialName) {
		set("material_name", materialName);
		return (M)this;
	}
	
	public java.lang.String getMaterialName() {
		return getStr("material_name");
	}

	public M setMaterialType(java.lang.String materialType) {
		set("material_type", materialType);
		return (M)this;
	}
	
	public java.lang.String getMaterialType() {
		return getStr("material_type");
	}

	public M setMaterialUnit(java.lang.String materialUnit) {
		set("material_unit", materialUnit);
		return (M)this;
	}
	
	public java.lang.String getMaterialUnit() {
		return getStr("material_unit");
	}

	public M setMaterialNum(java.lang.Integer materialNum) {
		set("material_num", materialNum);
		return (M)this;
	}
	
	public java.lang.Integer getMaterialNum() {
		return getInt("material_num");
	}

	public M setMaterialUnitPrice(java.math.BigDecimal materialUnitPrice) {
		set("material_unit_price", materialUnitPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getMaterialUnitPrice() {
		return get("material_unit_price");
	}

	public M setTotalMoney(java.math.BigDecimal totalMoney) {
		set("total_money", totalMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getTotalMoney() {
		return get("total_money");
	}

	public M setPurchaseId(java.lang.Integer purchaseId) {
		set("purchase_id", purchaseId);
		return (M)this;
	}
	
	public java.lang.Integer getPurchaseId() {
		return getInt("purchase_id");
	}

	public M setPurchaseDate(java.util.Date purchaseDate) {
		set("purchase_date", purchaseDate);
		return (M)this;
	}
	
	public java.util.Date getPurchaseDate() {
		return get("purchase_date");
	}

	public M setAuditId(java.lang.Integer auditId) {
		set("audit_id", auditId);
		return (M)this;
	}
	
	public java.lang.Integer getAuditId() {
		return getInt("audit_id");
	}

	public M setAuditDate(java.util.Date auditDate) {
		set("audit_date", auditDate);
		return (M)this;
	}
	
	public java.util.Date getAuditDate() {
		return get("audit_date");
	}

	public M setAuditStatus(java.lang.Integer auditStatus) {
		set("audit_status", auditStatus);
		return (M)this;
	}
	
	public java.lang.Integer getAuditStatus() {
		return getInt("audit_status");
	}

	public M setUsedNum(java.lang.Integer usedNum) {
		set("used_num", usedNum);
		return (M)this;
	}
	
	public java.lang.Integer getUsedNum() {
		return getInt("used_num");
	}

	public M setSerialNumber(java.lang.String serialNumber) {
		set("serial_number", serialNumber);
		return (M)this;
	}
	
	public java.lang.String getSerialNumber() {
		return getStr("serial_number");
	}

	public M setAccountId(java.lang.Integer accountId) {
		set("account_id", accountId);
		return (M)this;
	}
	
	public java.lang.Integer getAccountId() {
		return getInt("account_id");
	}

}
