package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbStockAdjustHistory<M extends BaseTbStockAdjustHistory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setStockId(java.lang.Integer stockId) {
		set("stock_id", stockId);
		return (M)this;
	}
	
	public java.lang.Integer getStockId() {
		return getInt("stock_id");
	}

	public M setAdjustStock(java.math.BigDecimal adjustStock) {
		set("adjust_stock", adjustStock);
		return (M)this;
	}
	
	public java.math.BigDecimal getAdjustStock() {
		return get("adjust_stock");
	}

	public M setAdjustDate(java.util.Date adjustDate) {
		set("adjust_date", adjustDate);
		return (M)this;
	}
	
	public java.util.Date getAdjustDate() {
		return get("adjust_date");
	}

	public M setAdjustor(java.lang.String adjustor) {
		set("adjustor", adjustor);
		return (M)this;
	}
	
	public java.lang.String getAdjustor() {
		return getStr("adjustor");
	}

	public M setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
		return (M)this;
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}

}
