package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbThreePartiesReceivables<M extends BaseTbThreePartiesReceivables<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
		return (M)this;
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}

	public M setCustomerPackId(java.lang.String customerPackId) {
		set("customer_pack_id", customerPackId);
		return (M)this;
	}
	
	public java.lang.String getCustomerPackId() {
		return getStr("customer_pack_id");
	}

	public M setThreeCompaniesId(java.lang.Integer threeCompaniesId) {
		set("three_companies_id", threeCompaniesId);
		return (M)this;
	}
	
	public java.lang.Integer getThreeCompaniesId() {
		return getInt("three_companies_id");
	}

	public M setPaymentRatio(java.math.BigDecimal paymentRatio) {
		set("payment_ratio", paymentRatio);
		return (M)this;
	}
	
	public java.math.BigDecimal getPaymentRatio() {
		return get("payment_ratio");
	}

	public M setPayableMoney(java.math.BigDecimal payableMoney) {
		set("payable_money", payableMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getPayableMoney() {
		return get("payable_money");
	}

	public M setProduceMoney(java.math.BigDecimal produceMoney) {
		set("produce_money", produceMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getProduceMoney() {
		return get("produce_money");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}
	
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
		return (M)this;
	}
	
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}
	
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
		return (M)this;
	}
	
	public java.lang.String getDelFlag() {
		return getStr("del_flag");
	}

	public M setSettledMoney(java.math.BigDecimal settledMoney) {
		set("settled_money", settledMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getSettledMoney() {
		return get("settled_money");
	}

	public M setBesettledMoney(java.math.BigDecimal besettledMoney) {
		set("besettled_money", besettledMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getBesettledMoney() {
		return get("besettled_money");
	}

	public M setSettleMoney(java.math.BigDecimal settleMoney) {
		set("settle_money", settleMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getSettleMoney() {
		return get("settle_money");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
