package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbCustomerPackInvoice<M extends BaseTbCustomerPackInvoice<M>> extends Model<M> implements IBean {

	public M setCustPackInvoId(java.lang.Integer custPackInvoId) {
		set("cust_pack_invo_id", custPackInvoId);
		return (M)this;
	}
	
	public java.lang.Integer getCustPackInvoId() {
		return getInt("cust_pack_invo_id");
	}

	public M setCustPackId(java.lang.String custPackId) {
		set("cust_pack_id", custPackId);
		return (M)this;
	}
	
	public java.lang.String getCustPackId() {
		return getStr("cust_pack_id");
	}

	public M setShPackId(java.lang.String shPackId) {
		set("sh_pack_id", shPackId);
		return (M)this;
	}
	
	public java.lang.String getShPackId() {
		return getStr("sh_pack_id");
	}

	public M setReceiveCompanyId(java.lang.Integer receiveCompanyId) {
		set("receive_company_id", receiveCompanyId);
		return (M)this;
	}
	
	public java.lang.Integer getReceiveCompanyId() {
		return getInt("receive_company_id");
	}

	public M setProvideCompanyId(java.lang.Integer provideCompanyId) {
		set("provide_company_id", provideCompanyId);
		return (M)this;
	}
	
	public java.lang.Integer getProvideCompanyId() {
		return getInt("provide_company_id");
	}

	public M setInvoiceMoney(java.math.BigDecimal invoiceMoney) {
		set("invoice_money", invoiceMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getInvoiceMoney() {
		return get("invoice_money");
	}

	public M setTaxRate(java.math.BigDecimal taxRate) {
		set("tax_rate", taxRate);
		return (M)this;
	}
	
	public java.math.BigDecimal getTaxRate() {
		return get("tax_rate");
	}

	public M setTaxMoney(java.math.BigDecimal taxMoney) {
		set("tax_money", taxMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getTaxMoney() {
		return get("tax_money");
	}

	public M setTotalMoney(java.math.BigDecimal totalMoney) {
		set("total_money", totalMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getTotalMoney() {
		return get("total_money");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setCreateUserId(java.lang.Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}
	
	public java.lang.Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public M setAuditUserId(java.lang.Integer auditUserId) {
		set("audit_user_id", auditUserId);
		return (M)this;
	}
	
	public java.lang.Integer getAuditUserId() {
		return getInt("audit_user_id");
	}

	public M setAuditDate(java.util.Date auditDate) {
		set("audit_date", auditDate);
		return (M)this;
	}
	
	public java.util.Date getAuditDate() {
		return get("audit_date");
	}

	public M setModifiyDate(java.util.Date modifiyDate) {
		set("modifiy_date", modifiyDate);
		return (M)this;
	}
	
	public java.util.Date getModifiyDate() {
		return get("modifiy_date");
	}

	public M setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.Integer getDeleteFlag() {
		return getInt("delete_flag");
	}

}
