package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbOilGasCardPack<M extends BaseTbOilGasCardPack<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setSalesUnit(java.lang.String salesUnit) {
		set("sales_unit", salesUnit);
		return (M)this;
	}
	
	public java.lang.String getSalesUnit() {
		return getStr("sales_unit");
	}

	public M setBranchGroupId(java.lang.Integer branchGroupId) {
		set("branch_group_id", branchGroupId);
		return (M)this;
	}
	
	public java.lang.Integer getBranchGroupId() {
		return getInt("branch_group_id");
	}

	public M setCardType(java.lang.Integer cardType) {
		set("card_type", cardType);
		return (M)this;
	}
	
	public java.lang.Integer getCardType() {
		return getInt("card_type");
	}

	public M setCardUnit(java.lang.String cardUnit) {
		set("card_unit", cardUnit);
		return (M)this;
	}
	
	public java.lang.String getCardUnit() {
		return getStr("card_unit");
	}

	public M setPurchaseId(java.lang.Integer purchaseId) {
		set("purchase_id", purchaseId);
		return (M)this;
	}
	
	public java.lang.Integer getPurchaseId() {
		return getInt("purchase_id");
	}

	public M setPurchaseDate(java.util.Date purchaseDate) {
		set("purchase_date", purchaseDate);
		return (M)this;
	}
	
	public java.util.Date getPurchaseDate() {
		return get("purchase_date");
	}

	public M setAuditId(java.lang.Integer auditId) {
		set("audit_id", auditId);
		return (M)this;
	}
	
	public java.lang.Integer getAuditId() {
		return getInt("audit_id");
	}

	public M setAuditDate(java.util.Date auditDate) {
		set("audit_date", auditDate);
		return (M)this;
	}
	
	public java.util.Date getAuditDate() {
		return get("audit_date");
	}

	public M setAuditStatus(java.lang.Integer auditStatus) {
		set("audit_status", auditStatus);
		return (M)this;
	}
	
	public java.lang.Integer getAuditStatus() {
		return getInt("audit_status");
	}

	public M setAccountId(java.lang.String accountId) {
		set("account_id", accountId);
		return (M)this;
	}
	
	public java.lang.String getAccountId() {
		return getStr("account_id");
	}

}
