package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbCustomerCheckingConf<M extends BaseTbCustomerCheckingConf<M>> extends Model<M> implements IBean {

	public M setCustCheckConId(java.lang.String custCheckConId) {
		set("cust_check_con_id", custCheckConId);
		return (M)this;
	}
	
	public java.lang.String getCustCheckConId() {
		return getStr("cust_check_con_id");
	}

	public M setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
		return (M)this;
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}

	public M setStartDate(java.util.Date startDate) {
		set("start_date", startDate);
		return (M)this;
	}
	
	public java.util.Date getStartDate() {
		return get("start_date");
	}

	public M setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
		return (M)this;
	}
	
	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public M setCheckingStatus(java.lang.Integer checkingStatus) {
		set("checking_status", checkingStatus);
		return (M)this;
	}
	
	public java.lang.Integer getCheckingStatus() {
		return getInt("checking_status");
	}

	public M setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.Integer getDeleteFlag() {
		return getInt("delete_flag");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setCreateUserId(java.lang.Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}
	
	public java.lang.Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public M setModifiyDate(java.util.Date modifiyDate) {
		set("modifiy_date", modifiyDate);
		return (M)this;
	}
	
	public java.util.Date getModifiyDate() {
		return get("modifiy_date");
	}

	public M setOrderCount(java.lang.Integer orderCount) {
		set("order_count", orderCount);
		return (M)this;
	}
	
	public java.lang.Integer getOrderCount() {
		return getInt("order_count");
	}

	public M setPreviousOrderCount(java.lang.Integer previousOrderCount) {
		set("previous_order_count", previousOrderCount);
		return (M)this;
	}
	
	public java.lang.Integer getPreviousOrderCount() {
		return getInt("previous_order_count");
	}

	public M setTotalWeight(java.math.BigDecimal totalWeight) {
		set("total_weight", totalWeight);
		return (M)this;
	}
	
	public java.math.BigDecimal getTotalWeight() {
		return get("total_weight");
	}

	public M setTotalPiece(java.lang.Integer totalPiece) {
		set("total_piece", totalPiece);
		return (M)this;
	}
	
	public java.lang.Integer getTotalPiece() {
		return getInt("total_piece");
	}

	public M setProduceMoney(java.math.BigDecimal produceMoney) {
		set("produce_money", produceMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getProduceMoney() {
		return get("produce_money");
	}

	public M setTaxRate(java.math.BigDecimal taxRate) {
		set("tax_rate", taxRate);
		return (M)this;
	}
	
	public java.math.BigDecimal getTaxRate() {
		return get("tax_rate");
	}

	public M setTaxMoney(java.math.BigDecimal taxMoney) {
		set("tax_money", taxMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getTaxMoney() {
		return get("tax_money");
	}

	public M setBusCheckingStatus(java.lang.Integer busCheckingStatus) {
		set("bus_checking_status", busCheckingStatus);
		return (M)this;
	}
	
	public java.lang.Integer getBusCheckingStatus() {
		return getInt("bus_checking_status");
	}

	public M setBusOrderCount(java.lang.Integer busOrderCount) {
		set("bus_order_count", busOrderCount);
		return (M)this;
	}
	
	public java.lang.Integer getBusOrderCount() {
		return getInt("bus_order_count");
	}

	public M setBusOrderMoney(java.math.BigDecimal busOrderMoney) {
		set("bus_order_money", busOrderMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getBusOrderMoney() {
		return get("bus_order_money");
	}

	public M setReceiveCheckingStatus(java.lang.Integer receiveCheckingStatus) {
		set("receive_checking_status", receiveCheckingStatus);
		return (M)this;
	}
	
	public java.lang.Integer getReceiveCheckingStatus() {
		return getInt("receive_checking_status");
	}

	public M setReceiveOrderCount(java.lang.Integer receiveOrderCount) {
		set("receive_order_count", receiveOrderCount);
		return (M)this;
	}
	
	public java.lang.Integer getReceiveOrderCount() {
		return getInt("receive_order_count");
	}

	public M setReceiveOrderMoney(java.math.BigDecimal receiveOrderMoney) {
		set("receive_order_money", receiveOrderMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getReceiveOrderMoney() {
		return get("receive_order_money");
	}

	public M setTrainCheckingStatus(java.lang.Integer trainCheckingStatus) {
		set("train_checking_status", trainCheckingStatus);
		return (M)this;
	}
	
	public java.lang.Integer getTrainCheckingStatus() {
		return getInt("train_checking_status");
	}

	public M setTrainOrderCount(java.lang.Integer trainOrderCount) {
		set("train_order_count", trainOrderCount);
		return (M)this;
	}
	
	public java.lang.Integer getTrainOrderCount() {
		return getInt("train_order_count");
	}

	public M setTrainOrderMoney(java.math.BigDecimal trainOrderMoney) {
		set("train_order_money", trainOrderMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getTrainOrderMoney() {
		return get("train_order_money");
	}

	public M setDeliCheckingStatus(java.lang.Integer deliCheckingStatus) {
		set("deli_checking_status", deliCheckingStatus);
		return (M)this;
	}
	
	public java.lang.Integer getDeliCheckingStatus() {
		return getInt("deli_checking_status");
	}

	public M setDeliOrderCount(java.lang.Integer deliOrderCount) {
		set("deli_order_count", deliOrderCount);
		return (M)this;
	}
	
	public java.lang.Integer getDeliOrderCount() {
		return getInt("deli_order_count");
	}

	public M setDeliOrderMoney(java.math.BigDecimal deliOrderMoney) {
		set("deli_order_money", deliOrderMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getDeliOrderMoney() {
		return get("deli_order_money");
	}

}
