package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbShortPack<M extends BaseTbShortPack<M>> extends Model<M> implements IBean {

	public M setShPackId(java.lang.String shPackId) {
		set("sh_pack_id", shPackId);
		return (M)this;
	}
	
	public java.lang.String getShPackId() {
		return getStr("sh_pack_id");
	}

	public M setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
		return (M)this;
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}

	public M setCheckingStatus(java.lang.Integer checkingStatus) {
		set("checking_status", checkingStatus);
		return (M)this;
	}
	
	public java.lang.Integer getCheckingStatus() {
		return getInt("checking_status");
	}

	public M setCashSettleStatus(java.lang.Integer cashSettleStatus) {
		set("cash_settle_status", cashSettleStatus);
		return (M)this;
	}
	
	public java.lang.Integer getCashSettleStatus() {
		return getInt("cash_settle_status");
	}

	public M setSuppliesSettleStatus(java.lang.Integer suppliesSettleStatus) {
		set("supplies_settle_status", suppliesSettleStatus);
		return (M)this;
	}
	
	public java.lang.Integer getSuppliesSettleStatus() {
		return getInt("supplies_settle_status");
	}

	public M setSettleStatus(java.lang.Integer settleStatus) {
		set("settle_status", settleStatus);
		return (M)this;
	}
	
	public java.lang.Integer getSettleStatus() {
		return getInt("settle_status");
	}

	public M setPackTruckNum(java.lang.Integer packTruckNum) {
		set("pack_truck_num", packTruckNum);
		return (M)this;
	}
	
	public java.lang.Integer getPackTruckNum() {
		return getInt("pack_truck_num");
	}

	public M setPaymentId(java.lang.Integer paymentId) {
		set("payment_id", paymentId);
		return (M)this;
	}
	
	public java.lang.Integer getPaymentId() {
		return getInt("payment_id");
	}

	public M setPackTruckDegree(java.lang.Integer packTruckDegree) {
		set("pack_truck_degree", packTruckDegree);
		return (M)this;
	}
	
	public java.lang.Integer getPackTruckDegree() {
		return getInt("pack_truck_degree");
	}

	public M setPayRatio(java.math.BigDecimal payRatio) {
		set("pay_ratio", payRatio);
		return (M)this;
	}
	
	public java.math.BigDecimal getPayRatio() {
		return get("pay_ratio");
	}

	public M setCashPayType(java.lang.Integer cashPayType) {
		set("cash_pay_type", cashPayType);
		return (M)this;
	}
	
	public java.lang.Integer getCashPayType() {
		return getInt("cash_pay_type");
	}

	public M setSuppliesReceiveType(java.lang.Integer suppliesReceiveType) {
		set("supplies_receive_type", suppliesReceiveType);
		return (M)this;
	}
	
	public java.lang.Integer getSuppliesReceiveType() {
		return getInt("supplies_receive_type");
	}

	public M setReceiveUserId(java.lang.Integer receiveUserId) {
		set("receive_user_id", receiveUserId);
		return (M)this;
	}
	
	public java.lang.Integer getReceiveUserId() {
		return getInt("receive_user_id");
	}

	public M setReceiver(java.lang.String receiver) {
		set("receiver", receiver);
		return (M)this;
	}
	
	public java.lang.String getReceiver() {
		return getStr("receiver");
	}

	public M setOpenBank(java.lang.String openBank) {
		set("open_bank", openBank);
		return (M)this;
	}
	
	public java.lang.String getOpenBank() {
		return getStr("open_bank");
	}

	public M setBankAccount(java.lang.String bankAccount) {
		set("bank_account", bankAccount);
		return (M)this;
	}
	
	public java.lang.String getBankAccount() {
		return getStr("bank_account");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.Integer getDeleteFlag() {
		return getInt("delete_flag");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setCreateUserId(java.lang.Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}
	
	public java.lang.Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public M setModifiyDate(java.util.Date modifiyDate) {
		set("modifiy_date", modifiyDate);
		return (M)this;
	}
	
	public java.util.Date getModifiyDate() {
		return get("modifiy_date");
	}

	public M setFreightChargeAmount(java.math.BigDecimal freightChargeAmount) {
		set("freight_charge_amount", freightChargeAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getFreightChargeAmount() {
		return get("freight_charge_amount");
	}

	public M setCashAmount(java.math.BigDecimal cashAmount) {
		set("cash_amount", cashAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getCashAmount() {
		return get("cash_amount");
	}

	public M setSuppliesAmount(java.math.BigDecimal suppliesAmount) {
		set("supplies_amount", suppliesAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getSuppliesAmount() {
		return get("supplies_amount");
	}

	public M setCheckingAuditor(java.lang.Integer checkingAuditor) {
		set("checkingAuditor", checkingAuditor);
		return (M)this;
	}
	
	public java.lang.Integer getCheckingAuditor() {
		return getInt("checkingAuditor");
	}

	public M setCheckingAuditDate(java.util.Date checkingAuditDate) {
		set("checking_audit_date", checkingAuditDate);
		return (M)this;
	}
	
	public java.util.Date getCheckingAuditDate() {
		return get("checking_audit_date");
	}

	public M setSettleAuditDate(java.util.Date settleAuditDate) {
		set("settle_audit_date", settleAuditDate);
		return (M)this;
	}
	
	public java.util.Date getSettleAuditDate() {
		return get("settle_audit_date");
	}

	public M setProvideCompanyId(java.lang.Integer provideCompanyId) {
		set("provide_company_id", provideCompanyId);
		return (M)this;
	}
	
	public java.lang.Integer getProvideCompanyId() {
		return getInt("provide_company_id");
	}

	public M setSuppliesType(java.lang.Integer suppliesType) {
		set("supplies_type", suppliesType);
		return (M)this;
	}
	
	public java.lang.Integer getSuppliesType() {
		return getInt("supplies_type");
	}

	public M setOilgascardId(java.lang.String oilgascardId) {
		set("oilgascard_id", oilgascardId);
		return (M)this;
	}
	
	public java.lang.String getOilgascardId() {
		return getStr("oilgascard_id");
	}

	public M setAuditId(java.lang.Integer auditId) {
		set("audit_id", auditId);
		return (M)this;
	}
	
	public java.lang.Integer getAuditId() {
		return getInt("audit_id");
	}

	public M setSuppliesExecuteId(java.lang.Integer suppliesExecuteId) {
		set("supplies_execute_id", suppliesExecuteId);
		return (M)this;
	}
	
	public java.lang.Integer getSuppliesExecuteId() {
		return getInt("supplies_execute_id");
	}

	public M setSuppliesExecuteDate(java.util.Date suppliesExecuteDate) {
		set("supplies_execute_date", suppliesExecuteDate);
		return (M)this;
	}
	
	public java.util.Date getSuppliesExecuteDate() {
		return get("supplies_execute_date");
	}

	public M setReceiveUserType(java.lang.Integer receiveUserType) {
		set("receive_user_type", receiveUserType);
		return (M)this;
	}
	
	public java.lang.Integer getReceiveUserType() {
		return getInt("receive_user_type");
	}

	public M setDotAccountPackId(java.lang.String dotAccountPackId) {
		set("dot_account_pack_id", dotAccountPackId);
		return (M)this;
	}
	
	public java.lang.String getDotAccountPackId() {
		return getStr("dot_account_pack_id");
	}

}
