package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbCargo<M extends BaseTbCargo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCargoName(java.lang.String cargoName) {
		set("cargo_name", cargoName);
		return (M)this;
	}
	
	public java.lang.String getCargoName() {
		return getStr("cargo_name");
	}

	public M setCargoCode(java.lang.String cargoCode) {
		set("cargo_code", cargoCode);
		return (M)this;
	}
	
	public java.lang.String getCargoCode() {
		return getStr("cargo_code");
	}

}
