package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbAdjustAccount<M extends BaseTbAdjustAccount<M>> extends Model<M> implements IBean {

	public M setAdjustAccountId(java.lang.String adjustAccountId) {
		set("adjust_account_id", adjustAccountId);
		return (M)this;
	}
	
	public java.lang.String getAdjustAccountId() {
		return getStr("adjust_account_id");
	}

	public M setAdjustCode(java.lang.String adjustCode) {
		set("adjust_code", adjustCode);
		return (M)this;
	}
	
	public java.lang.String getAdjustCode() {
		return getStr("adjust_code");
	}

	public M setExpenditureAccountId(java.lang.Integer expenditureAccountId) {
		set("expenditure_account_id", expenditureAccountId);
		return (M)this;
	}
	
	public java.lang.Integer getExpenditureAccountId() {
		return getInt("expenditure_account_id");
	}

	public M setDepositAccountId(java.lang.Integer depositAccountId) {
		set("deposit_account_id", depositAccountId);
		return (M)this;
	}
	
	public java.lang.Integer getDepositAccountId() {
		return getInt("deposit_account_id");
	}

	public M setAdjustMoney(java.math.BigDecimal adjustMoney) {
		set("adjust_money", adjustMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getAdjustMoney() {
		return get("adjust_money");
	}

	public M setPayment(java.lang.Integer payment) {
		set("payment", payment);
		return (M)this;
	}
	
	public java.lang.Integer getPayment() {
		return getInt("payment");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}
	
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
		return (M)this;
	}
	
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}
	
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
		return (M)this;
	}
	
	public java.lang.String getDelFlag() {
		return getStr("del_flag");
	}

}
