package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbShPackOrder<M extends BaseTbShPackOrder<M>> extends Model<M> implements IBean {

	public M setShPackOrderId(java.lang.String shPackOrderId) {
		set("sh_pack_order_id", shPackOrderId);
		return (M)this;
	}
	
	public java.lang.String getShPackOrderId() {
		return getStr("sh_pack_order_id");
	}

	public M setShPackId(java.lang.String shPackId) {
		set("sh_pack_id", shPackId);
		return (M)this;
	}
	
	public java.lang.String getShPackId() {
		return getStr("sh_pack_id");
	}

	public M setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
		return (M)this;
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public M setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.Integer getDeleteFlag() {
		return getInt("delete_flag");
	}

	public M setShOrderFinId(java.lang.String shOrderFinId) {
		set("sh_order_fin_id", shOrderFinId);
		return (M)this;
	}
	
	public java.lang.String getShOrderFinId() {
		return getStr("sh_order_fin_id");
	}

}
