package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbShortBarge<M extends BaseTbShortBarge<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
		return (M)this;
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}

	public M setShortBargeName(java.lang.String shortBargeName) {
		set("short_barge_name", shortBargeName);
		return (M)this;
	}
	
	public java.lang.String getShortBargeName() {
		return getStr("short_barge_name");
	}

	public M setShortBargeId(java.lang.Integer shortBargeId) {
		set("short_barge_id", shortBargeId);
		return (M)this;
	}
	
	public java.lang.Integer getShortBargeId() {
		return getInt("short_barge_id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setTransportPrice(java.math.BigDecimal transportPrice) {
		set("transport_price", transportPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getTransportPrice() {
		return get("transport_price");
	}

	public M setDeductionRate(java.lang.Float deductionRate) {
		set("deduction_rate", deductionRate);
		return (M)this;
	}
	
	public java.lang.Float getDeductionRate() {
		return getFloat("deduction_rate");
	}

	public M setDeductionPrice(java.math.BigDecimal deductionPrice) {
		set("deduction_price", deductionPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getDeductionPrice() {
		return get("deduction_price");
	}

	public M setPayment(java.lang.Integer payment) {
		set("payment", payment);
		return (M)this;
	}
	
	public java.lang.Integer getPayment() {
		return getInt("payment");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setShortBargeType(java.lang.Integer shortBargeType) {
		set("short_barge_type", shortBargeType);
		return (M)this;
	}
	
	public java.lang.Integer getShortBargeType() {
		return getInt("short_barge_type");
	}

}
