package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbContainer<M extends BaseTbContainer<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setContainerTypeId(java.lang.Integer containerTypeId) {
		set("container_type_id", containerTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getContainerTypeId() {
		return getInt("container_type_id");
	}

	public M setContainerNum(java.lang.String containerNum) {
		set("container_num", containerNum);
		return (M)this;
	}
	
	public java.lang.String getContainerNum() {
		return getStr("container_num");
	}

	public M setEastContainer(java.lang.String eastContainer) {
		set("east_container", eastContainer);
		return (M)this;
	}
	
	public java.lang.String getEastContainer() {
		return getStr("east_container");
	}

	public M setContainerKind(java.lang.String containerKind) {
		set("container_kind", containerKind);
		return (M)this;
	}
	
	public java.lang.String getContainerKind() {
		return getStr("container_kind");
	}

	public M setContainerCode(java.lang.String containerCode) {
		set("container_code", containerCode);
		return (M)this;
	}
	
	public java.lang.String getContainerCode() {
		return getStr("container_code");
	}

	public M setContainerId(java.lang.String containerId) {
		set("container_id", containerId);
		return (M)this;
	}
	
	public java.lang.String getContainerId() {
		return getStr("container_id");
	}

	public M setLength(java.lang.Integer length) {
		set("length", length);
		return (M)this;
	}
	
	public java.lang.Integer getLength() {
		return getInt("length");
	}

	public M setWidth(java.lang.Integer width) {
		set("width", width);
		return (M)this;
	}
	
	public java.lang.Integer getWidth() {
		return getInt("width");
	}

	public M setHight(java.lang.Integer hight) {
		set("hight", hight);
		return (M)this;
	}
	
	public java.lang.Integer getHight() {
		return getInt("hight");
	}

	public M setSize(java.lang.Integer size) {
		set("size", size);
		return (M)this;
	}
	
	public java.lang.Integer getSize() {
		return getInt("size");
	}

	public M setVolume(java.lang.Integer volume) {
		set("volume", volume);
		return (M)this;
	}
	
	public java.lang.Integer getVolume() {
		return getInt("volume");
	}

	public M setSelfWeight(java.lang.Integer selfWeight) {
		set("self_weight", selfWeight);
		return (M)this;
	}
	
	public java.lang.Integer getSelfWeight() {
		return getInt("self_weight");
	}

	public M setWeight(java.lang.Integer weight) {
		set("weight", weight);
		return (M)this;
	}
	
	public java.lang.Integer getWeight() {
		return getInt("weight");
	}

	public M setTrainLocationId(java.lang.Integer trainLocationId) {
		set("train_location_id", trainLocationId);
		return (M)this;
	}
	
	public java.lang.Integer getTrainLocationId() {
		return getInt("train_location_id");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
		return (M)this;
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}

}
