package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbMapPoint<M extends BaseTbMapPoint<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
		return (M)this;
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}

	public M setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
		return (M)this;
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public M setLon(java.math.BigDecimal lon) {
		set("lon", lon);
		return (M)this;
	}
	
	public java.math.BigDecimal getLon() {
		return get("lon");
	}

	public M setLat(java.math.BigDecimal lat) {
		set("lat", lat);
		return (M)this;
	}
	
	public java.math.BigDecimal getLat() {
		return get("lat");
	}

	public M setPosition(java.lang.String position) {
		set("position", position);
		return (M)this;
	}
	
	public java.lang.String getPosition() {
		return getStr("position");
	}

	public M setCarId(java.lang.String carId) {
		set("car_id", carId);
		return (M)this;
	}
	
	public java.lang.String getCarId() {
		return getStr("car_id");
	}

	public M setCarNo(java.lang.String carNo) {
		set("car_no", carNo);
		return (M)this;
	}
	
	public java.lang.String getCarNo() {
		return getStr("car_no");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setHistoryFlag(java.lang.Integer historyFlag) {
		set("history_flag", historyFlag);
		return (M)this;
	}
	
	public java.lang.Integer getHistoryFlag() {
		return getInt("history_flag");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setCreateUserId(java.lang.Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}
	
	public java.lang.Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setUpdateUserId(java.lang.Integer updateUserId) {
		set("update_user_id", updateUserId);
		return (M)this;
	}
	
	public java.lang.Integer getUpdateUserId() {
		return getInt("update_user_id");
	}

}
