package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbFinanceAccount<M extends BaseTbFinanceAccount<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setAccountOpeningTime(java.util.Date accountOpeningTime) {
		set("account_opening_time", accountOpeningTime);
		return (M)this;
	}
	
	public java.util.Date getAccountOpeningTime() {
		return get("account_opening_time");
	}

	public M setAccountKind(java.lang.Integer accountKind) {
		set("account_kind", accountKind);
		return (M)this;
	}
	
	public java.lang.Integer getAccountKind() {
		return getInt("account_kind");
	}

	public M setAccountType(java.lang.Integer accountType) {
		set("account_type", accountType);
		return (M)this;
	}
	
	public java.lang.Integer getAccountType() {
		return getInt("account_type");
	}

	public M setChooseAccountId(java.lang.Integer chooseAccountId) {
		set("choose_account_id", chooseAccountId);
		return (M)this;
	}
	
	public java.lang.Integer getChooseAccountId() {
		return getInt("choose_account_id");
	}

	public M setStartAccountBalance(java.math.BigDecimal startAccountBalance) {
		set("start_account_balance", startAccountBalance);
		return (M)this;
	}
	
	public java.math.BigDecimal getStartAccountBalance() {
		return get("start_account_balance");
	}

	public M setAccountBalance(java.math.BigDecimal accountBalance) {
		set("account_balance", accountBalance);
		return (M)this;
	}
	
	public java.math.BigDecimal getAccountBalance() {
		return get("account_balance");
	}

	public M setVigilanceAmount(java.math.BigDecimal vigilanceAmount) {
		set("vigilance_amount", vigilanceAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getVigilanceAmount() {
		return get("vigilance_amount");
	}

	public M setNonUseAmount(java.math.BigDecimal nonUseAmount) {
		set("non_use_amount", nonUseAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getNonUseAmount() {
		return get("non_use_amount");
	}

	public M setAccountName(java.lang.String accountName) {
		set("account_name", accountName);
		return (M)this;
	}
	
	public java.lang.String getAccountName() {
		return getStr("account_name");
	}

	public M setAccountNum(java.lang.String accountNum) {
		set("account_num", accountNum);
		return (M)this;
	}
	
	public java.lang.String getAccountNum() {
		return getStr("account_num");
	}

	public M setOpenBank(java.lang.String openBank) {
		set("open_bank", openBank);
		return (M)this;
	}
	
	public java.lang.String getOpenBank() {
		return getStr("open_bank");
	}

	public M setBankNum(java.lang.String bankNum) {
		set("bank_num", bankNum);
		return (M)this;
	}
	
	public java.lang.String getBankNum() {
		return getStr("bank_num");
	}

	public M setTaxIdentificationNumber(java.lang.String taxIdentificationNumber) {
		set("tax_identification_number", taxIdentificationNumber);
		return (M)this;
	}
	
	public java.lang.String getTaxIdentificationNumber() {
		return getStr("tax_identification_number");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
