package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbTrainOrder<M extends BaseTbTrainOrder<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
		return (M)this;
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}

	public M setProjectCode(java.lang.String projectCode) {
		set("project_code", projectCode);
		return (M)this;
	}
	
	public java.lang.String getProjectCode() {
		return getStr("project_code");
	}

	public M setProjectType(java.lang.Integer projectType) {
		set("project_type", projectType);
		return (M)this;
	}
	
	public java.lang.Integer getProjectType() {
		return getInt("project_type");
	}

	public M setBranchId(java.lang.Integer branchId) {
		set("branch_id", branchId);
		return (M)this;
	}
	
	public java.lang.Integer getBranchId() {
		return getInt("branch_id");
	}

	public M setBranchName(java.lang.String branchName) {
		set("branch_name", branchName);
		return (M)this;
	}
	
	public java.lang.String getBranchName() {
		return getStr("branch_name");
	}

	public M setBeginSite(java.lang.String beginSite) {
		set("begin_site", beginSite);
		return (M)this;
	}
	
	public java.lang.String getBeginSite() {
		return getStr("begin_site");
	}

	public M setBeginPlace(java.lang.String beginPlace) {
		set("begin_place", beginPlace);
		return (M)this;
	}
	
	public java.lang.String getBeginPlace() {
		return getStr("begin_place");
	}

	public M setEndSite(java.lang.String endSite) {
		set("end_site", endSite);
		return (M)this;
	}
	
	public java.lang.String getEndSite() {
		return getStr("end_site");
	}

	public M setEndPlace(java.lang.String endPlace) {
		set("end_place", endPlace);
		return (M)this;
	}
	
	public java.lang.String getEndPlace() {
		return getStr("end_place");
	}

	public M setPleaseCarNum(java.lang.String pleaseCarNum) {
		set("please_car_num", pleaseCarNum);
		return (M)this;
	}
	
	public java.lang.String getPleaseCarNum() {
		return getStr("please_car_num");
	}

	public M setPleaseCarTypeId(java.lang.Integer pleaseCarTypeId) {
		set("please_car_type_id", pleaseCarTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getPleaseCarTypeId() {
		return getInt("please_car_type_id");
	}

	public M setEstimateWeight(java.lang.String estimateWeight) {
		set("estimate_weight", estimateWeight);
		return (M)this;
	}
	
	public java.lang.String getEstimateWeight() {
		return getStr("estimate_weight");
	}

	public M setEstimateCost(java.lang.String estimateCost) {
		set("estimate_cost", estimateCost);
		return (M)this;
	}
	
	public java.lang.String getEstimateCost() {
		return getStr("estimate_cost");
	}

	public M setCargoName(java.lang.String cargoName) {
		set("cargo_name", cargoName);
		return (M)this;
	}
	
	public java.lang.String getCargoName() {
		return getStr("cargo_name");
	}

	public M setCargoSpecifications(java.lang.String cargoSpecifications) {
		set("cargo_specifications", cargoSpecifications);
		return (M)this;
	}
	
	public java.lang.String getCargoSpecifications() {
		return getStr("cargo_specifications");
	}

	public M setAdvanceChargeAccount(java.lang.String advanceChargeAccount) {
		set("advance_charge_account", advanceChargeAccount);
		return (M)this;
	}
	
	public java.lang.String getAdvanceChargeAccount() {
		return getStr("advance_charge_account");
	}

	public M setAdvanceCharge(java.math.BigDecimal advanceCharge) {
		set("advance_charge", advanceCharge);
		return (M)this;
	}
	
	public java.math.BigDecimal getAdvanceCharge() {
		return get("advance_charge");
	}

	public M setSureCarNum(java.lang.Integer sureCarNum) {
		set("sure_car_num", sureCarNum);
		return (M)this;
	}
	
	public java.lang.Integer getSureCarNum() {
		return getInt("sure_car_num");
	}

	public M setSendDate(java.util.Date sendDate) {
		set("send_date", sendDate);
		return (M)this;
	}
	
	public java.util.Date getSendDate() {
		return get("send_date");
	}

	public M setSendOperatorId(java.lang.String sendOperatorId) {
		set("send_operator_id", sendOperatorId);
		return (M)this;
	}
	
	public java.lang.String getSendOperatorId() {
		return getStr("send_operator_id");
	}

	public M setUpdateLocationId(java.lang.Integer updateLocationId) {
		set("update_location_id", updateLocationId);
		return (M)this;
	}
	
	public java.lang.Integer getUpdateLocationId() {
		return getInt("update_location_id");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setPleaseTrainNumber(java.lang.String pleaseTrainNumber) {
		set("please_train_number", pleaseTrainNumber);
		return (M)this;
	}
	
	public java.lang.String getPleaseTrainNumber() {
		return getStr("please_train_number");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setEntruckDate(java.util.Date entruckDate) {
		set("entruck_date", entruckDate);
		return (M)this;
	}
	
	public java.util.Date getEntruckDate() {
		return get("entruck_date");
	}

	public M setLoseCarNum(java.lang.Integer loseCarNum) {
		set("lose_car_num", loseCarNum);
		return (M)this;
	}
	
	public java.lang.Integer getLoseCarNum() {
		return getInt("lose_car_num");
	}

	public M setIsException(java.lang.Integer isException) {
		set("is_exception", isException);
		return (M)this;
	}
	
	public java.lang.Integer getIsException() {
		return getInt("is_exception");
	}

	public M setExceptionReason(java.lang.String exceptionReason) {
		set("exception_reason", exceptionReason);
		return (M)this;
	}
	
	public java.lang.String getExceptionReason() {
		return getStr("exception_reason");
	}

	public M setExceptionReportDate(java.util.Date exceptionReportDate) {
		set("exception_report_date", exceptionReportDate);
		return (M)this;
	}
	
	public java.util.Date getExceptionReportDate() {
		return get("exception_report_date");
	}

	public M setExceptionReportPerson(java.lang.String exceptionReportPerson) {
		set("exception_report_person", exceptionReportPerson);
		return (M)this;
	}
	
	public java.lang.String getExceptionReportPerson() {
		return getStr("exception_report_person");
	}

	public M setDeleteDate(java.util.Date deleteDate) {
		set("delete_date", deleteDate);
		return (M)this;
	}
	
	public java.util.Date getDeleteDate() {
		return get("delete_date");
	}

	public M setDeletePerson(java.lang.String deletePerson) {
		set("delete_person", deletePerson);
		return (M)this;
	}
	
	public java.lang.String getDeletePerson() {
		return getStr("delete_person");
	}

	public M setDeleteReason(java.lang.String deleteReason) {
		set("delete_reason", deleteReason);
		return (M)this;
	}
	
	public java.lang.String getDeleteReason() {
		return getStr("delete_reason");
	}

	public M setArtificialReportId(java.lang.Integer artificialReportId) {
		set("artificial_report_id", artificialReportId);
		return (M)this;
	}
	
	public java.lang.Integer getArtificialReportId() {
		return getInt("artificial_report_id");
	}

	public M setEntruckNumbe(java.lang.Integer entruckNumbe) {
		set("entruck_numbe", entruckNumbe);
		return (M)this;
	}
	
	public java.lang.Integer getEntruckNumbe() {
		return getInt("entruck_numbe");
	}

	public M setContainerNums(java.lang.Integer containerNums) {
		set("container_nums", containerNums);
		return (M)this;
	}
	
	public java.lang.Integer getContainerNums() {
		return getInt("container_nums");
	}

	public M setEntruckWeight(java.math.BigDecimal entruckWeight) {
		set("entruck_weight", entruckWeight);
		return (M)this;
	}
	
	public java.math.BigDecimal getEntruckWeight() {
		return get("entruck_weight");
	}

	public M setArriveWeight(java.math.BigDecimal arriveWeight) {
		set("arrive_weight", arriveWeight);
		return (M)this;
	}
	
	public java.math.BigDecimal getArriveWeight() {
		return get("arrive_weight");
	}

	public M setArriveDate(java.util.Date arriveDate) {
		set("arrive_date", arriveDate);
		return (M)this;
	}
	
	public java.util.Date getArriveDate() {
		return get("arrive_date");
	}

	public M setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.Integer getDeleteFlag() {
		return getInt("delete_flag");
	}

	public M setSendCompany(java.lang.String sendCompany) {
		set("send_company", sendCompany);
		return (M)this;
	}
	
	public java.lang.String getSendCompany() {
		return getStr("send_company");
	}

	public M setReceiptCompany(java.lang.String receiptCompany) {
		set("receipt_company", receiptCompany);
		return (M)this;
	}
	
	public java.lang.String getReceiptCompany() {
		return getStr("receipt_company");
	}

	public M setCheckcustFlag(java.lang.Integer checkcustFlag) {
		set("checkcust_flag", checkcustFlag);
		return (M)this;
	}
	
	public java.lang.Integer getCheckcustFlag() {
		return getInt("checkcust_flag");
	}

}
