package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbUserAnchoredCompany<M extends BaseTbUserAnchoredCompany<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public M setAnchoredCompanyId(java.lang.Integer anchoredCompanyId) {
		set("anchored_company_id", anchoredCompanyId);
		return (M)this;
	}
	
	public java.lang.Integer getAnchoredCompanyId() {
		return getInt("anchored_company_id");
	}

	public M setAnchoredDate(java.util.Date anchoredDate) {
		set("anchored_date", anchoredDate);
		return (M)this;
	}
	
	public java.util.Date getAnchoredDate() {
		return get("anchored_date");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setIsStop(java.lang.Integer isStop) {
		set("is_stop", isStop);
		return (M)this;
	}
	
	public java.lang.Integer getIsStop() {
		return getInt("is_stop");
	}

}
