package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbPoint<M extends BaseTbPoint<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setPointName(java.lang.String pointName) {
		set("point_name", pointName);
		return (M)this;
	}
	
	public java.lang.String getPointName() {
		return getStr("point_name");
	}

	public M setPointMin(java.lang.Integer pointMin) {
		set("point_min", pointMin);
		return (M)this;
	}
	
	public java.lang.Integer getPointMin() {
		return getInt("point_min");
	}

	public M setPointMax(java.lang.Integer pointMax) {
		set("point_max", pointMax);
		return (M)this;
	}
	
	public java.lang.Integer getPointMax() {
		return getInt("point_max");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setCargoId(java.lang.Integer cargoId) {
		set("cargo_id", cargoId);
		return (M)this;
	}
	
	public java.lang.Integer getCargoId() {
		return getInt("cargo_id");
	}

}
