package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbSmsPlan<M extends BaseTbSmsPlan<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setPoint(java.lang.Integer point) {
		set("point", point);
		return (M)this;
	}
	
	public java.lang.Integer getPoint() {
		return getInt("point");
	}

	public M setSmsModelId(java.lang.Integer smsModelId) {
		set("sms_model_id", smsModelId);
		return (M)this;
	}
	
	public java.lang.Integer getSmsModelId() {
		return getInt("sms_model_id");
	}

	public M setSmsModelCode(java.lang.String smsModelCode) {
		set("sms_model_code", smsModelCode);
		return (M)this;
	}
	
	public java.lang.String getSmsModelCode() {
		return getStr("sms_model_code");
	}

	public M setReceiveId(java.lang.Integer receiveId) {
		set("receive_id", receiveId);
		return (M)this;
	}
	
	public java.lang.Integer getReceiveId() {
		return getInt("receive_id");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setIsStop(java.lang.Integer isStop) {
		set("is_stop", isStop);
		return (M)this;
	}
	
	public java.lang.Integer getIsStop() {
		return getInt("is_stop");
	}

}
