package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbSmsSend<M extends BaseTbSmsSend<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSendTime(java.util.Date sendTime) {
		set("send_time", sendTime);
		return (M)this;
	}
	
	public java.util.Date getSendTime() {
		return get("send_time");
	}

	public M setRecivePhone(java.lang.String recivePhone) {
		set("recive_phone", recivePhone);
		return (M)this;
	}
	
	public java.lang.String getRecivePhone() {
		return getStr("recive_phone");
	}

	public M setMsg(java.lang.String msg) {
		set("msg", msg);
		return (M)this;
	}
	
	public java.lang.String getMsg() {
		return getStr("msg");
	}

	public M setReciveUserId(java.lang.Integer reciveUserId) {
		set("recive_user_id", reciveUserId);
		return (M)this;
	}
	
	public java.lang.Integer getReciveUserId() {
		return getInt("recive_user_id");
	}

	public M setReciveUserName(java.lang.String reciveUserName) {
		set("recive_user_name", reciveUserName);
		return (M)this;
	}
	
	public java.lang.String getReciveUserName() {
		return getStr("recive_user_name");
	}

	public M setOrderCode(java.lang.String orderCode) {
		set("order_code", orderCode);
		return (M)this;
	}
	
	public java.lang.String getOrderCode() {
		return getStr("order_code");
	}

	public M setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
		return (M)this;
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public M setMsgStatus(java.lang.Integer msgStatus) {
		set("msg_status", msgStatus);
		return (M)this;
	}
	
	public java.lang.Integer getMsgStatus() {
		return getInt("msg_status");
	}

	public M setOptUserName(java.lang.String optUserName) {
		set("opt_user_name", optUserName);
		return (M)this;
	}
	
	public java.lang.String getOptUserName() {
		return getStr("opt_user_name");
	}

	public M setOptUserId(java.lang.Integer optUserId) {
		set("opt_user_id", optUserId);
		return (M)this;
	}
	
	public java.lang.Integer getOptUserId() {
		return getInt("opt_user_id");
	}

	public M setMsgSignName(java.lang.String msgSignName) {
		set("msg_sign_name", msgSignName);
		return (M)this;
	}
	
	public java.lang.String getMsgSignName() {
		return getStr("msg_sign_name");
	}

}
