package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbExceptionMsg<M extends BaseTbExceptionMsg<M>> extends Model<M> implements IBean {

	public M setExceptionId(java.lang.String exceptionId) {
		set("exception_id", exceptionId);
		return (M)this;
	}
	
	public java.lang.String getExceptionId() {
		return getStr("exception_id");
	}

	public M setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
		return (M)this;
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}

	public M setProjectCode(java.lang.String projectCode) {
		set("project_code", projectCode);
		return (M)this;
	}
	
	public java.lang.String getProjectCode() {
		return getStr("project_code");
	}

	public M setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
		return (M)this;
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public M setOrderCode(java.lang.String orderCode) {
		set("order_code", orderCode);
		return (M)this;
	}
	
	public java.lang.String getOrderCode() {
		return getStr("order_code");
	}

	public M setTrainOrderId(java.lang.Integer trainOrderId) {
		set("train_order_id", trainOrderId);
		return (M)this;
	}
	
	public java.lang.Integer getTrainOrderId() {
		return getInt("train_order_id");
	}

	public M setShortTrainFlag(java.lang.Integer shortTrainFlag) {
		set("short_train_flag", shortTrainFlag);
		return (M)this;
	}
	
	public java.lang.Integer getShortTrainFlag() {
		return getInt("short_train_flag");
	}

	public M setNodeId(java.lang.String nodeId) {
		set("node_id", nodeId);
		return (M)this;
	}
	
	public java.lang.String getNodeId() {
		return getStr("node_id");
	}

	public M setNodeType(java.lang.String nodeType) {
		set("node_type", nodeType);
		return (M)this;
	}
	
	public java.lang.String getNodeType() {
		return getStr("node_type");
	}

	public M setOrderStatus(java.lang.Integer orderStatus) {
		set("order_status", orderStatus);
		return (M)this;
	}
	
	public java.lang.Integer getOrderStatus() {
		return getInt("order_status");
	}

	public M setCarPlateNumber(java.lang.String carPlateNumber) {
		set("car_plate_number", carPlateNumber);
		return (M)this;
	}
	
	public java.lang.String getCarPlateNumber() {
		return getStr("car_plate_number");
	}

	public M setCargoName(java.lang.String cargoName) {
		set("cargo_name", cargoName);
		return (M)this;
	}
	
	public java.lang.String getCargoName() {
		return getStr("cargo_name");
	}

	public M setSendCompany(java.lang.String sendCompany) {
		set("send_company", sendCompany);
		return (M)this;
	}
	
	public java.lang.String getSendCompany() {
		return getStr("send_company");
	}

	public M setReceiptCompany(java.lang.String receiptCompany) {
		set("receipt_company", receiptCompany);
		return (M)this;
	}
	
	public java.lang.String getReceiptCompany() {
		return getStr("receipt_company");
	}

	public M setExceptionReasonId(java.lang.Integer exceptionReasonId) {
		set("exception_reason_id", exceptionReasonId);
		return (M)this;
	}
	
	public java.lang.Integer getExceptionReasonId() {
		return getInt("exception_reason_id");
	}

	public M setExceptionReason(java.lang.String exceptionReason) {
		set("exception_reason", exceptionReason);
		return (M)this;
	}
	
	public java.lang.String getExceptionReason() {
		return getStr("exception_reason");
	}

	public M setExceptionReasonDetail(java.lang.String exceptionReasonDetail) {
		set("exception_reason_detail", exceptionReasonDetail);
		return (M)this;
	}
	
	public java.lang.String getExceptionReasonDetail() {
		return getStr("exception_reason_detail");
	}

	public M setExceptionSource(java.lang.Integer exceptionSource) {
		set("exception_source", exceptionSource);
		return (M)this;
	}
	
	public java.lang.Integer getExceptionSource() {
		return getInt("exception_source");
	}

	public M setSubmitUserId(java.lang.Integer submitUserId) {
		set("submit_user_id", submitUserId);
		return (M)this;
	}
	
	public java.lang.Integer getSubmitUserId() {
		return getInt("submit_user_id");
	}

	public M setSubmitDate(java.util.Date submitDate) {
		set("submit_date", submitDate);
		return (M)this;
	}
	
	public java.util.Date getSubmitDate() {
		return get("submit_date");
	}

	public M setAffirmStatus(java.lang.Integer affirmStatus) {
		set("affirm_status", affirmStatus);
		return (M)this;
	}
	
	public java.lang.Integer getAffirmStatus() {
		return getInt("affirm_status");
	}

	public M setAffirmUserId(java.lang.Integer affirmUserId) {
		set("affirm_user_id", affirmUserId);
		return (M)this;
	}
	
	public java.lang.Integer getAffirmUserId() {
		return getInt("affirm_user_id");
	}

	public M setAffirmDate(java.util.Date affirmDate) {
		set("affirm_date", affirmDate);
		return (M)this;
	}
	
	public java.util.Date getAffirmDate() {
		return get("affirm_date");
	}

	public M setResolveStatus(java.lang.Integer resolveStatus) {
		set("resolve_status", resolveStatus);
		return (M)this;
	}
	
	public java.lang.Integer getResolveStatus() {
		return getInt("resolve_status");
	}

	public M setResolveDate(java.util.Date resolveDate) {
		set("resolve_date", resolveDate);
		return (M)this;
	}
	
	public java.util.Date getResolveDate() {
		return get("resolve_date");
	}

	public M setResolveUserId(java.lang.Integer resolveUserId) {
		set("resolve_user_id", resolveUserId);
		return (M)this;
	}
	
	public java.lang.Integer getResolveUserId() {
		return getInt("resolve_user_id");
	}

	public M setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.Integer getDeleteFlag() {
		return getInt("delete_flag");
	}

	public M setDeleteUserId(java.lang.Integer deleteUserId) {
		set("delete_user_id", deleteUserId);
		return (M)this;
	}
	
	public java.lang.Integer getDeleteUserId() {
		return getInt("delete_user_id");
	}

}
