package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbLoginUser<M extends BaseTbLoginUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public M setPasswd(java.lang.String passwd) {
		set("passwd", passwd);
		return (M)this;
	}
	
	public java.lang.String getPasswd() {
		return getStr("passwd");
	}

	public M setUserIcon(java.lang.String userIcon) {
		set("user_icon", userIcon);
		return (M)this;
	}
	
	public java.lang.String getUserIcon() {
		return getStr("user_icon");
	}

	public M setMobilePhone(java.lang.String mobilePhone) {
		set("mobile_phone", mobilePhone);
		return (M)this;
	}
	
	public java.lang.String getMobilePhone() {
		return getStr("mobile_phone");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setOrderStatus(java.lang.Integer orderStatus) {
		set("order_status", orderStatus);
		return (M)this;
	}
	
	public java.lang.Integer getOrderStatus() {
		return getInt("order_status");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setLastLoginDate(java.util.Date lastLoginDate) {
		set("last_login_date", lastLoginDate);
		return (M)this;
	}
	
	public java.util.Date getLastLoginDate() {
		return get("last_login_date");
	}

	public M setInformationId(java.lang.Integer informationId) {
		set("information_id", informationId);
		return (M)this;
	}
	
	public java.lang.Integer getInformationId() {
		return getInt("information_id");
	}

	public M setCarTeamId(java.lang.Integer carTeamId) {
		set("car_team_id", carTeamId);
		return (M)this;
	}
	
	public java.lang.Integer getCarTeamId() {
		return getInt("car_team_id");
	}

	public M setAnchoredDate(java.util.Date anchoredDate) {
		set("anchored_date", anchoredDate);
		return (M)this;
	}
	
	public java.util.Date getAnchoredDate() {
		return get("anchored_date");
	}

	public M setCheckedCode(java.lang.String checkedCode) {
		set("checked_code", checkedCode);
		return (M)this;
	}
	
	public java.lang.String getCheckedCode() {
		return getStr("checked_code");
	}

	public M setCheckedCodeDate(java.util.Date checkedCodeDate) {
		set("checked_code_date", checkedCodeDate);
		return (M)this;
	}
	
	public java.util.Date getCheckedCodeDate() {
		return get("checked_code_date");
	}

	public M setUserIdcard(java.lang.String userIdcard) {
		set("user_idcard", userIdcard);
		return (M)this;
	}
	
	public java.lang.String getUserIdcard() {
		return getStr("user_idcard");
	}

}
