package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbSystemScene<M extends BaseTbSystemScene<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSceneName(java.lang.String sceneName) {
		set("scene_name", sceneName);
		return (M)this;
	}
	
	public java.lang.String getSceneName() {
		return getStr("scene_name");
	}

	public M setBranchGroupId(java.lang.String branchGroupId) {
		set("branch_group_id", branchGroupId);
		return (M)this;
	}
	
	public java.lang.String getBranchGroupId() {
		return getStr("branch_group_id");
	}

	public M setReasonType(java.lang.Integer reasonType) {
		set("reason_type", reasonType);
		return (M)this;
	}
	
	public java.lang.Integer getReasonType() {
		return getInt("reason_type");
	}

	public M setReasonScale(java.lang.String reasonScale) {
		set("reason_scale", reasonScale);
		return (M)this;
	}
	
	public java.lang.String getReasonScale() {
		return getStr("reason_scale");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
