package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbCargoLocation<M extends BaseTbCargoLocation<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setTonnage(java.lang.Float tonnage) {
		set("tonnage", tonnage);
		return (M)this;
	}
	
	public java.lang.Float getTonnage() {
		return getFloat("tonnage");
	}

	public M setFreightYardId(java.lang.Integer freightYardId) {
		set("freight_yard_id", freightYardId);
		return (M)this;
	}
	
	public java.lang.Integer getFreightYardId() {
		return getInt("freight_yard_id");
	}

	public M setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.Integer getDeleteFlag() {
		return getInt("delete_flag");
	}

}
