package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbEnterpriseReceivables<M extends BaseTbEnterpriseReceivables<M>> extends Model<M> implements IBean {

	public M setEnterpriseReceivablesId(java.lang.String enterpriseReceivablesId) {
		set("enterprise_receivables_id", enterpriseReceivablesId);
		return (M)this;
	}
	
	public java.lang.String getEnterpriseReceivablesId() {
		return getStr("enterprise_receivables_id");
	}

	public M setCostPackId(java.lang.String costPackId) {
		set("cost_pack_id", costPackId);
		return (M)this;
	}
	
	public java.lang.String getCostPackId() {
		return getStr("cost_pack_id");
	}

	public M setSettleMoney(java.math.BigDecimal settleMoney) {
		set("settle_money", settleMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getSettleMoney() {
		return get("settle_money");
	}

	public M setAuditStatus(java.lang.Integer auditStatus) {
		set("audit_status", auditStatus);
		return (M)this;
	}
	
	public java.lang.Integer getAuditStatus() {
		return getInt("audit_status");
	}

	public M setReceiveAccount(java.lang.String receiveAccount) {
		set("receive_account", receiveAccount);
		return (M)this;
	}
	
	public java.lang.String getReceiveAccount() {
		return getStr("receive_account");
	}

	public M setSettleUserId(java.lang.String settleUserId) {
		set("settle_user_id", settleUserId);
		return (M)this;
	}
	
	public java.lang.String getSettleUserId() {
		return getStr("settle_user_id");
	}

	public M setSettleDate(java.util.Date settleDate) {
		set("settle_date", settleDate);
		return (M)this;
	}
	
	public java.util.Date getSettleDate() {
		return get("settle_date");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setAuditUserId(java.lang.String auditUserId) {
		set("audit_user_id", auditUserId);
		return (M)this;
	}
	
	public java.lang.String getAuditUserId() {
		return getStr("audit_user_id");
	}

	public M setAuditDate(java.util.Date auditDate) {
		set("audit_date", auditDate);
		return (M)this;
	}
	
	public java.util.Date getAuditDate() {
		return get("audit_date");
	}

	public M setBranchId(java.lang.Integer branchId) {
		set("branch_id", branchId);
		return (M)this;
	}
	
	public java.lang.Integer getBranchId() {
		return getInt("branch_id");
	}

	public M setDelFlag(java.lang.Integer delFlag) {
		set("del_flag", delFlag);
		return (M)this;
	}
	
	public java.lang.Integer getDelFlag() {
		return getInt("del_flag");
	}

}
