package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbBranchGroup<M extends BaseTbBranchGroup<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setShortName(java.lang.String shortName) {
		set("short_name", shortName);
		return (M)this;
	}
	
	public java.lang.String getShortName() {
		return getStr("short_name");
	}

	public M setShortCode(java.lang.String shortCode) {
		set("short_code", shortCode);
		return (M)this;
	}
	
	public java.lang.String getShortCode() {
		return getStr("short_code");
	}

	public M setAscriptionId(java.lang.Integer ascriptionId) {
		set("ascription_id", ascriptionId);
		return (M)this;
	}
	
	public java.lang.Integer getAscriptionId() {
		return getInt("ascription_id");
	}

	public M setAscriptionName(java.lang.String ascriptionName) {
		set("ascription_name", ascriptionName);
		return (M)this;
	}
	
	public java.lang.String getAscriptionName() {
		return getStr("ascription_name");
	}

	public M setLevel(java.lang.Integer level) {
		set("level", level);
		return (M)this;
	}
	
	public java.lang.Integer getLevel() {
		return getInt("level");
	}

	public M setResponsibler(java.lang.String responsibler) {
		set("responsibler", responsibler);
		return (M)this;
	}
	
	public java.lang.String getResponsibler() {
		return getStr("responsibler");
	}

	public M setResponsiblerId(java.lang.Integer responsiblerId) {
		set("responsiblerId", responsiblerId);
		return (M)this;
	}
	
	public java.lang.Integer getResponsiblerId() {
		return getInt("responsiblerId");
	}

	public M setAreaId(java.lang.String areaId) {
		set("area_id", areaId);
		return (M)this;
	}
	
	public java.lang.String getAreaId() {
		return getStr("area_id");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setRelationTrainLocationId(java.lang.Integer relationTrainLocationId) {
		set("relation_train_location_id", relationTrainLocationId);
		return (M)this;
	}
	
	public java.lang.Integer getRelationTrainLocationId() {
		return getInt("relation_train_location_id");
	}

	public M setRelationTrainLocationName(java.lang.String relationTrainLocationName) {
		set("relation_train_location_name", relationTrainLocationName);
		return (M)this;
	}
	
	public java.lang.String getRelationTrainLocationName() {
		return getStr("relation_train_location_name");
	}

	public M setRelationBeginLocationId(java.lang.Integer relationBeginLocationId) {
		set("relation_begin_location_id", relationBeginLocationId);
		return (M)this;
	}
	
	public java.lang.Integer getRelationBeginLocationId() {
		return getInt("relation_begin_location_id");
	}

	public M setRelationBeginLocation(java.lang.String relationBeginLocation) {
		set("relation_begin_location", relationBeginLocation);
		return (M)this;
	}
	
	public java.lang.String getRelationBeginLocation() {
		return getStr("relation_begin_location");
	}

	public M setComment(java.lang.String comment) {
		set("comment", comment);
		return (M)this;
	}
	
	public java.lang.String getComment() {
		return getStr("comment");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setDutyParagraph(java.lang.String dutyParagraph) {
		set("duty_paragraph", dutyParagraph);
		return (M)this;
	}
	
	public java.lang.String getDutyParagraph() {
		return getStr("duty_paragraph");
	}

	public M setSysOrgCode(java.lang.String sysOrgCode) {
		set("sys_org_code", sysOrgCode);
		return (M)this;
	}
	
	public java.lang.String getSysOrgCode() {
		return getStr("sys_org_code");
	}

}
