package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbCustomer<M extends BaseTbCustomer<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setAccount(java.lang.String account) {
		set("account", account);
		return (M)this;
	}
	
	public java.lang.String getAccount() {
		return getStr("account");
	}

	public M setPasswd(java.lang.String passwd) {
		set("passwd", passwd);
		return (M)this;
	}
	
	public java.lang.String getPasswd() {
		return getStr("passwd");
	}

	public M setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
		return (M)this;
	}
	
	public java.lang.String getCompanyName() {
		return getStr("company_name");
	}

	public M setShortName(java.lang.String shortName) {
		set("short_name", shortName);
		return (M)this;
	}
	
	public java.lang.String getShortName() {
		return getStr("short_name");
	}

	public M setBranchId(java.lang.Integer branchId) {
		set("branch_id", branchId);
		return (M)this;
	}
	
	public java.lang.Integer getBranchId() {
		return getInt("branch_id");
	}

	public M setAddressCode(java.lang.String addressCode) {
		set("address_code", addressCode);
		return (M)this;
	}
	
	public java.lang.String getAddressCode() {
		return getStr("address_code");
	}

	public M setDetailAddress(java.lang.String detailAddress) {
		set("detail_address", detailAddress);
		return (M)this;
	}
	
	public java.lang.String getDetailAddress() {
		return getStr("detail_address");
	}

	public M setCompanyContacts(java.lang.String companyContacts) {
		set("company_contacts", companyContacts);
		return (M)this;
	}
	
	public java.lang.String getCompanyContacts() {
		return getStr("company_contacts");
	}

	public M setDepartment(java.lang.String department) {
		set("department", department);
		return (M)this;
	}
	
	public java.lang.String getDepartment() {
		return getStr("department");
	}

	public M setStationPhone(java.lang.String stationPhone) {
		set("station_phone", stationPhone);
		return (M)this;
	}
	
	public java.lang.String getStationPhone() {
		return getStr("station_phone");
	}

	public M setStationFax(java.lang.String stationFax) {
		set("station_fax", stationFax);
		return (M)this;
	}
	
	public java.lang.String getStationFax() {
		return getStr("station_fax");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setBankAccount(java.lang.String bankAccount) {
		set("bank_account", bankAccount);
		return (M)this;
	}
	
	public java.lang.String getBankAccount() {
		return getStr("bank_account");
	}

	public M setAccountName(java.lang.String accountName) {
		set("account_name", accountName);
		return (M)this;
	}
	
	public java.lang.String getAccountName() {
		return getStr("account_name");
	}

	public M setOpenBank(java.lang.String openBank) {
		set("open_bank", openBank);
		return (M)this;
	}
	
	public java.lang.String getOpenBank() {
		return getStr("open_bank");
	}

	public M setOpenBankNum(java.lang.String openBankNum) {
		set("open_bank_num", openBankNum);
		return (M)this;
	}
	
	public java.lang.String getOpenBankNum() {
		return getStr("open_bank_num");
	}

	public M setDutyParagraph(java.lang.String dutyParagraph) {
		set("duty_paragraph", dutyParagraph);
		return (M)this;
	}
	
	public java.lang.String getDutyParagraph() {
		return getStr("duty_paragraph");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setRelationBeginLocation(java.lang.String relationBeginLocation) {
		set("relation_begin_location", relationBeginLocation);
		return (M)this;
	}
	
	public java.lang.String getRelationBeginLocation() {
		return getStr("relation_begin_location");
	}

}
