package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbCostOrderFinance<M extends BaseTbCostOrderFinance<M>> extends Model<M> implements IBean {

	public M setCostOrderFinId(java.lang.String costOrderFinId) {
		set("cost_order_fin_id", costOrderFinId);
		return (M)this;
	}
	
	public java.lang.String getCostOrderFinId() {
		return getStr("cost_order_fin_id");
	}

	public M setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
		return (M)this;
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}

	public M setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
		return (M)this;
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public M setFinaceStatus(java.lang.Integer finaceStatus) {
		set("finace_status", finaceStatus);
		return (M)this;
	}
	
	public java.lang.Integer getFinaceStatus() {
		return getInt("finace_status");
	}

	public M setPackFlag(java.lang.Integer packFlag) {
		set("pack_flag", packFlag);
		return (M)this;
	}
	
	public java.lang.Integer getPackFlag() {
		return getInt("pack_flag");
	}

	public M setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.Integer getDeleteFlag() {
		return getInt("delete_flag");
	}

	public M setSendTare(java.math.BigDecimal sendTare) {
		set("send_tare", sendTare);
		return (M)this;
	}
	
	public java.math.BigDecimal getSendTare() {
		return get("send_tare");
	}

	public M setSendGross(java.math.BigDecimal sendGross) {
		set("send_gross", sendGross);
		return (M)this;
	}
	
	public java.math.BigDecimal getSendGross() {
		return get("send_gross");
	}

	public M setSendNet(java.math.BigDecimal sendNet) {
		set("send_net", sendNet);
		return (M)this;
	}
	
	public java.math.BigDecimal getSendNet() {
		return get("send_net");
	}

	public M setCargoUnitPrice(java.math.BigDecimal cargoUnitPrice) {
		set("cargo_unit_price", cargoUnitPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getCargoUnitPrice() {
		return get("cargo_unit_price");
	}

	public M setCargoPrice(java.math.BigDecimal cargoPrice) {
		set("cargo_price", cargoPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getCargoPrice() {
		return get("cargo_price");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setCreateUserId(java.lang.Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}
	
	public java.lang.Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public M setModifiyDate(java.util.Date modifiyDate) {
		set("modifiy_date", modifiyDate);
		return (M)this;
	}
	
	public java.util.Date getModifiyDate() {
		return get("modifiy_date");
	}

	public M setTbCostPackId(java.lang.String tbCostPackId) {
		set("tb_cost_pack_id", tbCostPackId);
		return (M)this;
	}
	
	public java.lang.String getTbCostPackId() {
		return getStr("tb_cost_pack_id");
	}

}
