package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbCarTeam<M extends BaseTbCarTeam<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
		return (M)this;
	}
	
	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public M setAreaCode(java.lang.String areaCode) {
		set("area_code", areaCode);
		return (M)this;
	}
	
	public java.lang.String getAreaCode() {
		return getStr("area_code");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setSex(java.lang.Integer sex) {
		set("sex", sex);
		return (M)this;
	}
	
	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setIdcardNumber(java.lang.String idcardNumber) {
		set("idcard_number", idcardNumber);
		return (M)this;
	}
	
	public java.lang.String getIdcardNumber() {
		return getStr("idcard_number");
	}

	public M setIdcardPhotoFront(java.lang.String idcardPhotoFront) {
		set("idcard_photo_front", idcardPhotoFront);
		return (M)this;
	}
	
	public java.lang.String getIdcardPhotoFront() {
		return getStr("idcard_photo_front");
	}

	public M setIdcardPhotoBack(java.lang.String idcardPhotoBack) {
		set("idcard_photo_back", idcardPhotoBack);
		return (M)this;
	}
	
	public java.lang.String getIdcardPhotoBack() {
		return getStr("idcard_photo_back");
	}

	public M setCarItemName(java.lang.String carItemName) {
		set("car_item_name", carItemName);
		return (M)this;
	}
	
	public java.lang.String getCarItemName() {
		return getStr("car_item_name");
	}

	public M setOpenBank(java.lang.String openBank) {
		set("open_bank", openBank);
		return (M)this;
	}
	
	public java.lang.String getOpenBank() {
		return getStr("open_bank");
	}

	public M setBankCardNumber(java.lang.String bankCardNumber) {
		set("bank_card_number", bankCardNumber);
		return (M)this;
	}
	
	public java.lang.String getBankCardNumber() {
		return getStr("bank_card_number");
	}

}
