package com.qinlong.carmanage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbInvoice<M extends BaseTbInvoice<M>> extends Model<M> implements IBean {

	public M setInvoiceId(java.lang.String invoiceId) {
		set("invoice_id", invoiceId);
		return (M)this;
	}
	
	public java.lang.String getInvoiceId() {
		return getStr("invoice_id");
	}

	public M setPackId(java.lang.String packId) {
		set("pack_id", packId);
		return (M)this;
	}
	
	public java.lang.String getPackId() {
		return getStr("pack_id");
	}

	public M setPackType(java.lang.String packType) {
		set("pack_type", packType);
		return (M)this;
	}
	
	public java.lang.String getPackType() {
		return getStr("pack_type");
	}

	public M setReceiveCompanyName(java.lang.String receiveCompanyName) {
		set("receive_company_name", receiveCompanyName);
		return (M)this;
	}
	
	public java.lang.String getReceiveCompanyName() {
		return getStr("receive_company_name");
	}

	public M setReceiveType(java.lang.Integer receiveType) {
		set("receive_type", receiveType);
		return (M)this;
	}
	
	public java.lang.Integer getReceiveType() {
		return getInt("receive_type");
	}

	public M setReceiveCompanyId(java.lang.Integer receiveCompanyId) {
		set("receive_company_id", receiveCompanyId);
		return (M)this;
	}
	
	public java.lang.Integer getReceiveCompanyId() {
		return getInt("receive_company_id");
	}

	public M setProvideCompanyName(java.lang.String provideCompanyName) {
		set("provide_company_name", provideCompanyName);
		return (M)this;
	}
	
	public java.lang.String getProvideCompanyName() {
		return getStr("provide_company_name");
	}

	public M setProvideType(java.lang.Integer provideType) {
		set("provide_type", provideType);
		return (M)this;
	}
	
	public java.lang.Integer getProvideType() {
		return getInt("provide_type");
	}

	public M setProvideCompanyId(java.lang.Integer provideCompanyId) {
		set("provide_company_id", provideCompanyId);
		return (M)this;
	}
	
	public java.lang.Integer getProvideCompanyId() {
		return getInt("provide_company_id");
	}

	public M setInvoiceMoney(java.math.BigDecimal invoiceMoney) {
		set("invoice_money", invoiceMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getInvoiceMoney() {
		return get("invoice_money");
	}

	public M setTaxRate(java.math.BigDecimal taxRate) {
		set("tax_rate", taxRate);
		return (M)this;
	}
	
	public java.math.BigDecimal getTaxRate() {
		return get("tax_rate");
	}

	public M setTaxMoney(java.math.BigDecimal taxMoney) {
		set("tax_money", taxMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getTaxMoney() {
		return get("tax_money");
	}

	public M setTotalMoney(java.math.BigDecimal totalMoney) {
		set("total_money", totalMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getTotalMoney() {
		return get("total_money");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setCreateUserId(java.lang.Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}
	
	public java.lang.Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public M setAuditUserId(java.lang.Integer auditUserId) {
		set("audit_user_id", auditUserId);
		return (M)this;
	}
	
	public java.lang.Integer getAuditUserId() {
		return getInt("audit_user_id");
	}

	public M setAuditDate(java.util.Date auditDate) {
		set("audit_date", auditDate);
		return (M)this;
	}
	
	public java.util.Date getAuditDate() {
		return get("audit_date");
	}

	public M setBackUserId(java.lang.Integer backUserId) {
		set("back_user_id", backUserId);
		return (M)this;
	}
	
	public java.lang.Integer getBackUserId() {
		return getInt("back_user_id");
	}

	public M setBackDate(java.util.Date backDate) {
		set("back_date", backDate);
		return (M)this;
	}
	
	public java.util.Date getBackDate() {
		return get("back_date");
	}

	public M setBackOrgName(java.lang.String backOrgName) {
		set("back_org_name", backOrgName);
		return (M)this;
	}
	
	public java.lang.String getBackOrgName() {
		return getStr("back_org_name");
	}

	public M setModifiyDate(java.util.Date modifiyDate) {
		set("modifiy_date", modifiyDate);
		return (M)this;
	}
	
	public java.util.Date getModifiyDate() {
		return get("modifiy_date");
	}

	public M setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.Integer getDeleteFlag() {
		return getInt("delete_flag");
	}

	public M setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
		return (M)this;
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}

	public M setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
		return (M)this;
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public M setTrainFlag(java.lang.Integer trainFlag) {
		set("train_flag", trainFlag);
		return (M)this;
	}
	
	public java.lang.Integer getTrainFlag() {
		return getInt("train_flag");
	}

	public M setBeginAddress(java.lang.String beginAddress) {
		set("beginAddress", beginAddress);
		return (M)this;
	}
	
	public java.lang.String getBeginAddress() {
		return getStr("beginAddress");
	}

	public M setEndAddress(java.lang.String endAddress) {
		set("endAddress", endAddress);
		return (M)this;
	}
	
	public java.lang.String getEndAddress() {
		return getStr("endAddress");
	}

	public M setInvoiceStatus(java.lang.Integer invoiceStatus) {
		set("invoice_status", invoiceStatus);
		return (M)this;
	}
	
	public java.lang.Integer getInvoiceStatus() {
		return getInt("invoice_status");
	}

}
