package com.qinlong.carmanage.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("tb_account_record_detail", "id", TbAccountRecordDetail.class);
		arp.addMapping("tb_adjust_account", "adjust_account_id", TbAdjustAccount.class);
		arp.addMapping("tb_advance_charge", "id", TbAdvanceCharge.class);
		arp.addMapping("tb_anchore_record", "id", TbAnchoreRecord.class);
		arp.addMapping("tb_anchored_company", "id", TbAnchoredCompany.class);
		arp.addMapping("tb_branch_group", "id", TbBranchGroup.class);
		arp.addMapping("tb_branch_group_link", "id", TbBranchGroupLink.class);
		arp.addMapping("tb_branch_group_train_station", "id", TbBranchGroupTrainStation.class);
		arp.addMapping("tb_car_team", "id", TbCarTeam.class);
		arp.addMapping("tb_cargo", "id", TbCargo.class);
		arp.addMapping("tb_cargo_location", "id", TbCargoLocation.class);
		arp.addMapping("tb_container", "id", TbContainer.class);
		arp.addMapping("tb_container_type", "id", TbContainerType.class);
		arp.addMapping("tb_cost_order_finance", "cost_order_fin_id", TbCostOrderFinance.class);
		arp.addMapping("tb_cost_pack", "sh_pack_id", TbCostPack.class);
		arp.addMapping("tb_cust_settle", "id", TbCustSettle.class);
		arp.addMapping("tb_cust_settle_detail", "id", TbCustSettleDetail.class);
		arp.addMapping("tb_customer", "id", TbCustomer.class);
		arp.addMapping("tb_customer_branch_group", "id", TbCustomerBranchGroup.class);
		arp.addMapping("tb_customer_checking_conf", "cust_check_con_id", TbCustomerCheckingConf.class);
		arp.addMapping("tb_customer_pack", "cust_pack_id", TbCustomerPack.class);
		arp.addMapping("tb_customer_pack_invoice", "cust_pack_invo_id", TbCustomerPackInvoice.class);
		arp.addMapping("tb_customer_pack_order", "cust_pack_order_id", TbCustomerPackOrder.class);
		arp.addMapping("tb_dict", "id", TbDict.class);
		arp.addMapping("tb_dict_item", "id", TbDictItem.class);
		arp.addMapping("tb_dot_account_pack", "dot_account_pack_id", TbDotAccountPack.class);
		arp.addMapping("tb_enterprise_receivables", "enterprise_receivables_id", TbEnterpriseReceivables.class);
		arp.addMapping("tb_exception_msg", "exception_id", TbExceptionMsg.class);
		arp.addMapping("tb_finance_account", "id", TbFinanceAccount.class);
		arp.addMapping("tb_finance_account_detail", "id", TbFinanceAccountDetail.class);
		arp.addMapping("tb_freight_yard", "id", TbFreightYard.class);
		arp.addMapping("tb_history_location", "id", TbHistoryLocation.class);
		arp.addMapping("tb_invoice", "invoice_id", TbInvoice.class);
		arp.addMapping("tb_login_user", "id", TbLoginUser.class);
		arp.addMapping("tb_map_point", "id", TbMapPoint.class);
		arp.addMapping("tb_massage_code_record", "id", TbMassageCodeRecord.class);
		arp.addMapping("tb_material", "id", TbMaterial.class);
		arp.addMapping("tb_menu", "id", TbMenu.class);
		arp.addMapping("tb_notice", "id", TbNotice.class);
		arp.addMapping("tb_oil_gas_card", "id", TbOilGasCard.class);
		arp.addMapping("tb_oil_gas_card_pack", "id", TbOilGasCardPack.class);
		arp.addMapping("tb_order", "id", TbOrder.class);
		arp.addMapping("tb_order_operator", "id", TbOrderOperator.class);
		arp.addMapping("tb_payment", "id", TbPayment.class);
		arp.addMapping("tb_permission", "id", TbPermission.class);
		arp.addMapping("tb_plan_group", "id", TbPlanGroup.class);
		arp.addMapping("tb_plan_mange", "id", TbPlanMange.class);
		arp.addMapping("tb_point", "id", TbPoint.class);
		arp.addMapping("tb_project", "id", TbProject.class);
		arp.addMapping("tb_project_distribution", "id", TbProjectDistribution.class);
		arp.addMapping("tb_project_operation_log", "id", TbProjectOperationLog.class);
		arp.addMapping("tb_project_update_record", "id", TbProjectUpdateRecord.class);
		arp.addMapping("tb_road_info", "id", TbRoadInfo.class);
		arp.addMapping("tb_role", "id", TbRole.class);
		arp.addMapping("tb_role_menu", "id", TbRoleMenu.class);
		arp.addMapping("tb_role_perssion", "id", TbRolePerssion.class);
		arp.addMapping("tb_role_systemuser", "id", TbRoleSystemuser.class);
		arp.addMapping("tb_sh_pack_order", "sh_pack_order_id", TbShPackOrder.class);
		arp.addMapping("tb_short_barge", "id", TbShortBarge.class);
		arp.addMapping("tb_short_order_finance", "sh_order_fin_id", TbShortOrderFinance.class);
		arp.addMapping("tb_short_pack", "sh_pack_id", TbShortPack.class);
		arp.addMapping("tb_sms_code_model", "id", TbSmsCodeModel.class);
		arp.addMapping("tb_sms_plan", "id", TbSmsPlan.class);
		arp.addMapping("tb_sms_send", "id", TbSmsSend.class);
		arp.addMapping("tb_specifications", "id", TbSpecifications.class);
		arp.addMapping("tb_station_business", "id", TbStationBusiness.class);
		arp.addMapping("tb_stock", "id", TbStock.class);
		arp.addMapping("tb_stock_adjust_history", "id", TbStockAdjustHistory.class);
		arp.addMapping("tb_stock_charging", "id", TbStockCharging.class);
		arp.addMapping("tb_system_scene", "id", TbSystemScene.class);
		arp.addMapping("tb_system_user", "id", TbSystemUser.class);
		arp.addMapping("tb_three_parties_receivables", "id", TbThreePartiesReceivables.class);
		arp.addMapping("tb_three_parties_settle", "id", TbThreePartiesSettle.class);
		arp.addMapping("tb_train_order", "id", TbTrainOrder.class);
		arp.addMapping("tb_train_order_cargo_palce", "id", TbTrainOrderCargoPalce.class);
		arp.addMapping("tb_train_station", "id", TbTrainStation.class);
		arp.addMapping("tb_train_type", "id", TbTrainType.class);
		arp.addMapping("tb_user_anchored_company", "id", TbUserAnchoredCompany.class);
		arp.addMapping("tb_user_branch_group", "id", TbUserBranchGroup.class);
		arp.addMapping("tb_user_information", "id", TbUserInformation.class);
	}
}

