package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbAccountRecordDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbAccountRecordDetail extends BaseTbAccountRecordDetail<TbAccountRecordDetail> {
	
}
