package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbAdvanceCharge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbAdvanceCharge extends BaseTbAdvanceCharge<TbAdvanceCharge> {
	
}
