package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbAdjustAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbAdjustAccount extends BaseTbAdjustAccount<TbAdjustAccount> {
	
}
