package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbAnchoreRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbAnchoreRecord extends BaseTbAnchoreRecord<TbAnchoreRecord> {
	
}
