package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbAnchoredCompany;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbAnchoredCompany extends BaseTbAnchoredCompany<TbAnchoredCompany> {
	
}
