package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbBranchGroupTrainStation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbBranchGroupTrainStation extends BaseTbBranchGroupTrainStation<TbBranchGroupTrainStation> {
	
}
