package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbBranchGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbBranchGroup extends BaseTbBranchGroup<TbBranchGroup> {
	
}
