package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbBranchGroupLink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbBranchGroupLink extends BaseTbBranchGroupLink<TbBranchGroupLink> {
	
}
