package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbCargo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbCargo extends BaseTbCargo<TbCargo> {
	
}
