package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbCargoLocation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbCargoLocation extends BaseTbCargoLocation<TbCargoLocation> {
	
}
