package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbCarTeam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbCarTeam extends BaseTbCarTeam<TbCarTeam> {
	
}
