package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbContainer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbContainer extends BaseTbContainer<TbContainer> {
	
}
