package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbContainerType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbContainerType extends BaseTbContainerType<TbContainerType> {
	
}
