package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbCostOrderFinance;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbCostOrderFinance extends BaseTbCostOrderFinance<TbCostOrderFinance> {
	
}
