package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbCostPack;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbCostPack extends BaseTbCostPack<TbCostPack> {
	
}
