package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbCustomerPackOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbCustomerPackOrder extends BaseTbCustomerPackOrder<TbCustomerPackOrder> {
	
}
