package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbCustomerPackInvoice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbCustomerPackInvoice extends BaseTbCustomerPackInvoice<TbCustomerPackInvoice> {
	
}
