package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbCustomerCheckingConf;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbCustomerCheckingConf extends BaseTbCustomerCheckingConf<TbCustomerCheckingConf> {
	
}
