package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbCustSettle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbCustSettle extends BaseTbCustSettle<TbCustSettle> {
	
}
