package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbCustSettleDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbCustSettleDetail extends BaseTbCustSettleDetail<TbCustSettleDetail> {
	
}
