package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbCustomer extends BaseTbCustomer<TbCustomer> {
	
}
