package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbCustomerBranchGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbCustomerBranchGroup extends BaseTbCustomerBranchGroup<TbCustomerBranchGroup> {
	
}
