package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbCustomerPack;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbCustomerPack extends BaseTbCustomerPack<TbCustomerPack> {
	
}
