package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbDictItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbDictItem extends BaseTbDictItem<TbDictItem> {
	
}
