package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbDict extends BaseTbDict<TbDict> {
	
}
