package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbDotAccountPack;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbDotAccountPack extends BaseTbDotAccountPack<TbDotAccountPack> {
	
}
