package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbEnterpriseReceivables;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbEnterpriseReceivables extends BaseTbEnterpriseReceivables<TbEnterpriseReceivables> {
	
}
