package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbExceptionMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbExceptionMsg extends BaseTbExceptionMsg<TbExceptionMsg> {
	
}
