package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbFinanceAccountDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbFinanceAccountDetail extends BaseTbFinanceAccountDetail<TbFinanceAccountDetail> {
	
}
