package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbFinanceAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbFinanceAccount extends BaseTbFinanceAccount<TbFinanceAccount> {
	
}
