package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbFreightYard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbFreightYard extends BaseTbFreightYard<TbFreightYard> {
	
}
