package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbHistoryLocation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbHistoryLocation extends BaseTbHistoryLocation<TbHistoryLocation> {
	
}
