package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbInvoice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbInvoice extends BaseTbInvoice<TbInvoice> {
	
}
