package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbLoginUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbLoginUser extends BaseTbLoginUser<TbLoginUser> {
	
}
