package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbMassageCodeRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbMassageCodeRecord extends BaseTbMassageCodeRecord<TbMassageCodeRecord> {
	
}
