package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbMaterial;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbMaterial extends BaseTbMaterial<TbMaterial> {
	
}
