package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbMapPoint;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbMapPoint extends BaseTbMapPoint<TbMapPoint> {
	
}
