package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbMenu extends BaseTbMenu<TbMenu> {
	
}
