package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbNotice extends BaseTbNotice<TbNotice> {
	
}
