package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbOilGasCardPack;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbOilGasCardPack extends BaseTbOilGasCardPack<TbOilGasCardPack> {
	
}
