package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbOilGasCard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbOilGasCard extends BaseTbOilGasCard<TbOilGasCard> {
	
}
