package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbOrder extends BaseTbOrder<TbOrder> {
	
}
