package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbOrderOperator;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbOrderOperator extends BaseTbOrderOperator<TbOrderOperator> {
	
}
