package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbPayment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbPayment extends BaseTbPayment<TbPayment> {
	
}
