package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbPermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbPermission extends BaseTbPermission<TbPermission> {
	
}
