package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbPlanGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbPlanGroup extends BaseTbPlanGroup<TbPlanGroup> {
	
}
