package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbPlanMange;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbPlanMange extends BaseTbPlanMange<TbPlanMange> {
	
}
