package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbPoint;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbPoint extends BaseTbPoint<TbPoint> {
	
}
