package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbProjectOperationLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbProjectOperationLog extends BaseTbProjectOperationLog<TbProjectOperationLog> {
	
}
