package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbProject extends BaseTbProject<TbProject> {
	
}
