package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbProjectUpdateRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbProjectUpdateRecord extends BaseTbProjectUpdateRecord<TbProjectUpdateRecord> {
	
}
