package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbProjectDistribution;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbProjectDistribution extends BaseTbProjectDistribution<TbProjectDistribution> {
	
}
