package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbRoleSystemuser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbRoleSystemuser extends BaseTbRoleSystemuser<TbRoleSystemuser> {
	
}
