package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbRoadInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbRoadInfo extends BaseTbRoadInfo<TbRoadInfo> {
	
}
