package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbRolePerssion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbRolePerssion extends BaseTbRolePerssion<TbRolePerssion> {
	
}
