package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbRole extends BaseTbRole<TbRole> {
	
}
