package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbRoleMenu extends BaseTbRoleMenu<TbRoleMenu> {
	
}
