package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbShortBarge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbShortBarge extends BaseTbShortBarge<TbShortBarge> {
	
}
