package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbShPackOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbShPackOrder extends BaseTbShPackOrder<TbShPackOrder> {
	
}
