package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbShortOrderFinance;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbShortOrderFinance extends BaseTbShortOrderFinance<TbShortOrderFinance> {
	
}
