package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbShortPack;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbShortPack extends BaseTbShortPack<TbShortPack> {
	
}
