package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbSmsPlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbSmsPlan extends BaseTbSmsPlan<TbSmsPlan> {
	
}
