package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbSmsCodeModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbSmsCodeModel extends BaseTbSmsCodeModel<TbSmsCodeModel> {
	
}
