package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbSmsSend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbSmsSend extends BaseTbSmsSend<TbSmsSend> {
	
}
