package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbSpecifications;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbSpecifications extends BaseTbSpecifications<TbSpecifications> {
	
}
