package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbStockAdjustHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbStockAdjustHistory extends BaseTbStockAdjustHistory<TbStockAdjustHistory> {
	
}
