package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbStockCharging;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbStockCharging extends BaseTbStockCharging<TbStockCharging> {
	
}
