package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbStationBusiness;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbStationBusiness extends BaseTbStationBusiness<TbStationBusiness> {
	
}
