package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbStock;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbStock extends BaseTbStock<TbStock> {
	
}
