package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbSystemUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbSystemUser extends BaseTbSystemUser<TbSystemUser> {
	
}
