package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbSystemScene;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbSystemScene extends BaseTbSystemScene<TbSystemScene> {
	
}
