package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbThreePartiesReceivables;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbThreePartiesReceivables extends BaseTbThreePartiesReceivables<TbThreePartiesReceivables> {
	
}
