package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbThreePartiesSettle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbThreePartiesSettle extends BaseTbThreePartiesSettle<TbThreePartiesSettle> {
	
}
