package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbTrainOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbTrainOrder extends BaseTbTrainOrder<TbTrainOrder> {
	
}
