package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbTrainType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbTrainType extends BaseTbTrainType<TbTrainType> {
	
}
