package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbTrainStation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbTrainStation extends BaseTbTrainStation<TbTrainStation> {
	
}
