package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbTrainOrderCargoPalce;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbTrainOrderCargoPalce extends BaseTbTrainOrderCargoPalce<TbTrainOrderCargoPalce> {
	
}
