package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbUserAnchoredCompany;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbUserAnchoredCompany extends BaseTbUserAnchoredCompany<TbUserAnchoredCompany> {
	
}
