package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbUserBranchGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbUserBranchGroup extends BaseTbUserBranchGroup<TbUserBranchGroup> {
	
}
