package com.qinlong.carmanage.common.model;

import com.qinlong.carmanage.common.model.base.BaseTbUserInformation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbUserInformation extends BaseTbUserInformation<TbUserInformation> {
	
}
